/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /u/develop/mj001b/cvsroot/tools/2Dconv_2/lex.yy.c,v 1.1 2001/05/14 07:34:16 usr10656 Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 110
#define YY_END_OF_BUFFER 111
static yyconst short int yy_accept[407] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  111,  109,
      108,   96,  104,  101,  102,   99,   97,  103,   98,  107,
      100,  109,  109,  109,  109,  105,  106,   45,   57,  100,
      109,  109,  109,  109,  109,  109,  109,   61,   61,  110,
       61,   60,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   21,   98,  100,   25,   25,   25,   24,   25,

       25,   25,   25,   25,   25,   25,   25,   25,   25,   62,
      100,  109,  109,   66,   66,   66,   65,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   91,  100,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,   95,
       95,   95,   94,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   86,  100,   82,  109,  109,  109,   40,
      100,  109,  109,   44,   44,   44,   43,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   35,  100,  109,
      109,  109,  109,  109,  109,   39,   39,   39,   38,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,  100,

       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
      107,    1,    0,    0,    0,    0,    3,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   58,   59,   22,   23,
        5,    0,    0,   63,   64,    7,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   75,    0,   92,
       93,    9,   84,   83,   81,   80,    0,   11,    0,    0,
       41,   42,   13,    0,    0,    0,    0,    0,    0,   36,
       37,   15,    2,    4,    6,    8,   10,   12,   14,   16,
        0,   18,    0,    0,   51,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   87,    0,    0,   70,    0,    0,   85,
        0,    0,    0,    0,    0,   30,    0,    0,    0,    0,
        0,    0,   48,    0,    0,    0,   54,    0,    0,   53,
        0,   68,    0,    0,    0,    0,    0,   89,    0,   90,
       72,    0,    0,    0,    0,    0,   34,   32,    0,    0,
       31,    0,    0,    0,   46,    0,    0,    0,   47,    0,
        0,    0,   79,   74,    0,   78,    0,   88,    0,    0,
        0,    0,   28,   33,   29,   26,   20,   19,    0,   49,
       56,   52,   55,    0,   73,    0,   77,   76,   71,   27,

        0,   67,   69,    0,   50,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    1,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,    1,    1,
        1,    1,    1,    1,   15,    1,   16,    1,    1,   17,
        1,    1,   18,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   19,    1,    1,
        1,   20,    1,    1,    1,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,    1,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   46,    1,   47,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[48] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[415] =
    {   0,
        0,   46,   91,    0,  135,  181,  226,    0,  263,  309,
       38,   65,  355,  401,  444,    0,  484,  530,   12,   17,
       61,   82,  576,  622,  665,    0,  706,  752,   11,   31,
      798,  844,  375,  374,  373,  372,  371,  370,  369,  368,
      366,  365,  364,  363,  362,  361,  359,  346,  353,  892,
      892,  892,  892,  892,  892,  892,  892,  892,   28,   61,
      344,  328,  328,  324,  309,  892,  892,  892,  892,  339,
      311,  312,   48,   41,  308,  318,  307,  892,  892,  892,
      892,  892,  892,  892,  892,  892,  892,  892,  892,   74,
      892,  892,  892,  892,  892,  892,  892,  892,  892,  892,

      892,  892,  892,  892,  892,  892,   75,  892,  892,  892,
      333,  306,  304,  892,  892,  892,  892,  892,  892,  892,
      892,  892,  892,  892,   83,  892,  892,  892,  330,   57,
       72,  303,  307,  314,  297,   73,  308,  291,  306,  892,
      892,  892,  892,  892,  892,  892,  892,  892,  892,  892,
      100,  892,  892,  892,  322,  892,   82,   86,  310,  892,
      319,  303,  288,  892,  892,  892,  892,  892,  892,  892,
      892,  892,  892,  892,  113,  892,  892,  892,  316,  298,
      286,  279,  282,  269,  284,  892,  892,  892,  892,  892,
      892,  892,  892,  892,  892,  892,  117,  892,  892,  296,

      892,  892,  892,  892,  892,  290,  892,  892,  892,  892,
      892,  892,  289,  892,  288,  287,  286,  285,  284,  283,
      119,  892,  256,  264,  267,  271,  892,  248,  254,  255,
      249,  250,  257,   32,  248,  249,  892,  892,  892,  892,
      892,  258,  257,  892,  892,  892,  244,  252,  244,  245,
      251,  238,  233,  230,  223,  212,  213,  217,  217,  892,
      892,  892,  892,  892,  892,  892,  234,  892,  213,  230,
      892,  892,  892,  224,  212,  221,  207,  220,  215,  892,
      892,  892,  892,  892,  892,  892,  892,  892,  892,  892,
      214,  892,  203,  202,  892,  197,  210,  197,  208,  198,

      196,  197,  186,  191,  185,  197,  193,  188,  180,  183,
      184,  191,  181,  892,  172,  188,  177,  182,  171,  892,
      184,  185,  168,  180,  177,  892,  170,  164,  167,  163,
      159,  154,  159,  167,  161,  154,  892,  141,  154,  892,
      139,  892,  156,  151,  150,  137,  138,  892,  143,  892,
      892,  145,  125,  144,  134,  136,  892,  892,  127,  141,
      892,  130,  134,  124,  892,  122,  124,  120,  892,  133,
      114,  135,  892,  892,  117,  892,  129,  892,  126,  125,
      106,  111,  892,  892,  892,  892,  892,  892,   88,  892,
      892,  892,  892,   80,  892,   90,  892,  892,  892,  892,

       85,  892,  892,   75,  892,  892,   98,   64,   44,   22,
       18,   17,    4,    0
    } ;

static yyconst short int yy_def[415] =
    {   0,
      407,  407,    2,    3,  408,  408,    2,    7,  409,  409,
        7,    7,  410,  410,    2,   15,  411,  411,    7,    7,
        7,    7,  412,  412,    2,   25,  413,  413,    7,    7,
      414,  414,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,    0,  406,  406,  406,  406,
      406,  406,  406,  406
    } ;

static yyconst short int yy_nxt[940] =
    {   0,
      201,   51,   52,   53,  186,   54,   55,   56,   57,   58,
       59,   60,   61,   60,  154,   50,   50,  164,  140,  154,
       62,   50,  114,  200,  155,  156,  157,  158,  159,  155,
      156,  157,  158,  159,   63,   50,   64,   65,  221,  221,
       52,  221,  110,  200,   96,   66,   67,   51,   52,   53,
      111,   54,   55,   56,   57,   58,   59,   60,   61,   60,
      301,  232,  112,   52,   78,  160,   62,   52,  302,  110,
      113,  221,  221,  161,  221,  233,  230,  111,  237,  239,
       63,  162,   64,   65,   52,  231,  160,  244,  247,  112,
      248,   66,   67,   68,  161,   69,  249,  113,   50,  163,

      255,  256,  162,   70,  260,  263,  250,  238,  240,  265,
      405,   50,   71,  404,  403,   72,  245,  271,  402,  264,
      163,  280,   73,  266,  401,   50,   74,   50,   75,  221,
      221,   76,  221,  261,  400,   77,   79,   80,   81,   82,
       83,   84,   85,   86,   87,   88,  272,   89,  399,  398,
      281,  397,  396,  395,   90,  394,  393,  392,  391,  390,
      389,  388,  387,  386,  385,  384,  383,  382,  381,  380,
      379,  378,  377,  376,  375,  374,  373,  372,  371,  370,
       91,   92,   79,   80,   81,   82,   83,   84,   85,   86,
       87,   88,  369,   89,  368,  367,  366,  365,  364,  363,

       90,  362,  361,  360,  359,  358,  357,  356,  355,  354,
      353,  352,  351,  350,  349,  348,  347,  346,  345,  344,
      343,  342,  341,  340,  339,  338,   91,   92,   80,  337,
       93,  336,  335,  334,  333,  332,   94,   50,   95,   50,
      331,  330,  329,  328,  327,  326,   50,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
       50,  312,   50,   50,   97,   80,   98,   99,  100,  101,
      102,  103,  104,  105,  311,  106,  310,  309,  308,  307,
      306,  305,  107,  304,  303,  300,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,

      285,  284,  283,  282,  279,  278,  277,  276,  108,  109,
       97,   80,   98,   99,  100,  101,  102,  103,  104,  105,
      275,  106,  274,  273,  270,  269,  268,  267,  107,  262,
      259,  258,  257,  254,  253,  252,  251,  246,  243,  242,
      241,  236,  235,  234,  229,  228,  227,  226,  225,  224,
      223,  222,  406,  220,  108,  109,  115,   80,  116,  117,
      118,  119,  120,  121,  122,  123,  220,  124,  219,  219,
      218,  218,  217,  217,  125,  216,  216,  215,  215,  214,
      214,  213,  213,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      126,  127,  115,   80,  116,  117,  118,  119,  120,  121,
      122,  123,  406,  124,  406,  406,  406,  406,  406,  406,
      125,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  126,  127,  128,  406,
      406,  406,  406,  406,  406,  406,  129,  406,  406,  406,
      406,  406,  406,  406,  130,  406,  131,  406,  132,  406,
      406,  133,  406,  406,  406,  406,  134,  406,   50,  135,
       50,  136,  137,  138,  139,  141,   80,  142,  143,  144,
      145,  146,  147,  148,  149,  406,  150,  406,  406,  406,

      406,  406,  406,  151,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  152,
      153,  141,   80,  142,  143,  144,  145,  146,  147,  148,
      149,  406,  150,  406,  406,  406,  406,  406,  406,  151,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  152,  153,  165,   80,  166,
      167,  168,  169,  170,  171,  172,  173,  406,  174,  406,
      406,  406,  406,  406,  406,  175,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  176,  177,  165,   80,  166,  167,  168,  169,  170,
      171,  172,  173,  406,  174,  406,  406,  406,  406,  406,
      406,  175,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  176,  177,  178,
      406,  406,  406,  406,  406,  406,  406,  179,  406,  406,
      406,  406,  406,  406,  406,   50,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  180,  181,  406,   50,

      406,  182,  183,  184,  406,  406,  185,  187,   80,  188,
      189,  190,  191,  192,  193,  194,  195,  406,  196,  406,
      406,  406,  406,  406,  406,  197,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  198,  199,  187,   80,  188,  189,  190,  191,  192,
      193,  194,  195,  406,  196,  406,  406,  406,  406,  406,
      406,  197,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  198,  199,  202,

       80,  203,  406,  204,  205,  206,  207,  208,  209,  406,
      210,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  211,  212,  202,   80,  203,  406,  204,
      205,  206,  207,  208,  209,  406,  210,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  211,
      212,   49,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406
    } ;

static yyconst short int yy_chk[940] =
    {   0,
      414,    1,    1,    1,  413,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   19,   29,   19,  412,  411,   20,
        1,   20,  410,   29,   19,   19,   19,   19,   19,   20,
       20,   20,   20,   20,    1,   30,    1,    1,   59,   59,
       11,   59,   11,   30,  409,    1,    1,    2,    2,    2,
       11,    2,    2,    2,    2,    2,    2,    2,    2,    2,
      234,   74,   11,   21,  408,   21,    2,   12,  234,   12,
       11,   60,   60,   21,   60,   74,   73,   12,   90,  107,
        2,   21,    2,    2,   22,   73,   22,  125,  130,   12,
      130,    2,    2,    3,   22,    3,  131,   12,  407,   21,

      136,  136,   22,    3,  151,  157,  131,   90,  107,  158,
      404,    3,    3,  401,  396,    3,  125,  175,  394,  157,
       22,  197,    3,  158,  389,    3,    3,    3,    3,  221,
      221,    3,  221,  151,  382,    3,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,  175,    5,  381,  380,
      197,  379,  377,  375,    5,  372,  371,  370,  368,  367,
      366,  364,  363,  362,  360,  359,  356,  355,  354,  353,
      352,  349,  347,  346,  345,  344,  343,  341,  339,  338,
        5,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,  336,    6,  335,  334,  333,  332,  331,  330,

        6,  329,  328,  327,  325,  324,  323,  322,  321,  319,
      318,  317,  316,  315,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,    6,    6,    7,  301,
        7,  300,  299,  298,  297,  296,    7,    7,    7,    7,
      294,  293,  291,  279,  278,  277,    7,  276,  275,  274,
      270,  269,  267,  259,  258,  257,  256,  255,  254,  253,
        7,  252,    7,    7,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,  251,    9,  250,  249,  248,  247,
      243,  242,    9,  236,  235,  233,  232,  231,  230,  229,
      228,  226,  225,  224,  223,  220,  219,  218,  217,  216,

      215,  213,  206,  200,  185,  184,  183,  182,    9,    9,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
      181,   10,  180,  179,  163,  162,  161,  159,   10,  155,
      139,  138,  137,  135,  134,  133,  132,  129,  113,  112,
      111,   77,   76,   75,   72,   71,   70,   65,   64,   63,
       62,   61,   49,   48,   10,   10,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   47,   13,   46,   45,
       44,   43,   42,   41,   13,   40,   39,   38,   37,   36,
       35,   34,   33,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       13,   13,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,    0,   14,    0,    0,    0,    0,    0,    0,
       14,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   14,   14,   15,    0,
        0,    0,    0,    0,    0,    0,   15,    0,    0,    0,
        0,    0,    0,    0,   15,    0,   15,    0,   15,    0,
        0,   15,    0,    0,    0,    0,   15,    0,   15,   15,
       15,   15,   15,   15,   15,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,    0,   17,    0,    0,    0,

        0,    0,    0,   17,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   17,
       17,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,    0,   18,    0,    0,    0,    0,    0,    0,   18,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   18,   18,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,    0,   23,    0,
        0,    0,    0,    0,    0,   23,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   23,   23,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,    0,   24,    0,    0,    0,    0,    0,
        0,   24,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   24,   24,   25,
        0,    0,    0,    0,    0,    0,    0,   25,    0,    0,
        0,    0,    0,    0,    0,   25,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   25,   25,    0,   25,

        0,   25,   25,   25,    0,    0,   25,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,    0,   27,    0,
        0,    0,    0,    0,    0,   27,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   27,   27,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,    0,   28,    0,    0,    0,    0,    0,
        0,   28,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   28,   28,   31,

       31,   31,    0,   31,   31,   31,   31,   31,   31,    0,
       31,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   31,   31,   32,   32,   32,    0,   32,
       32,   32,   32,   32,   32,    0,   32,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   32,
       32,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "2d_layout.l"
#define INITIAL 0
#line 2 "2d_layout.l"
#include "util.h"

int num_line = 0;
char lexstrbuf[ 256 ] = {0};
int strcnt = 0;
#define DEF 1
#define DEFSTR 2
#define TRI 3
#define TRISTR 4
#define ST 5
#define STSTR 6
#define MODE 7
#define MDSTR 8
#define ALPHA 9
#define AC 10
#define ACSTR 11
#define TR 12
#define TRSTR 13
#define MORF 14

#define COMM 15
#define COMM_DEF 16
#define COMM_TRI 17
#define COMM_ST 18
#define COMM_MD 19
#define COMM_ALP 20
#define COMM_AC 21
#define COMM_TR 22
#define COMM_MF 23

#line 736 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 10 "2d_layout.l"

#line 889 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 407 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 892 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 11 "2d_layout.l"
{ BEGIN COMM; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 12 "2d_layout.l"
{ BEGIN INITIAL; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 14 "2d_layout.l"
{ BEGIN COMM_DEF; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 15 "2d_layout.l"
{ BEGIN DEF; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 17 "2d_layout.l"
{ BEGIN COMM_ST; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 18 "2d_layout.l"
{ BEGIN ST; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 20 "2d_layout.l"
{ BEGIN COMM_MD; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 21 "2d_layout.l"
{ BEGIN MODE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 23 "2d_layout.l"
{ BEGIN COMM_ALP; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 24 "2d_layout.l"
{ BEGIN ALPHA; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 26 "2d_layout.l"
{ BEGIN COMM_AC; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 27 "2d_layout.l"
{ BEGIN AC; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 29 "2d_layout.l"
{ BEGIN COMM_TR; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 30 "2d_layout.l"
{ BEGIN TR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 32 "2d_layout.l"
{ BEGIN COMM_MF; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 33 "2d_layout.l"
{ BEGIN MORF; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 35 "2d_layout.l"
;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 38 "2d_layout.l"
{
			  BEGIN DEF;
			  return OBJ;
			}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 42 "2d_layout.l"
{
			  BEGIN ST;
			  return STAT;
			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 47 "2d_layout.l"
{
			  BEGIN TRI;
			  return REFTRI;
			}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 51 "2d_layout.l"
{
			  BEGIN TRISTR;
			  strcnt = 0;
			}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 55 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\"'; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 56 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\n'; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 57 "2d_layout.l"
{
			  lexstrbuf[strcnt] = 0;
			  yylval.str = &poolbuf[pool(lexstrbuf)];
			  BEGIN INITIAL;
			  return STRING;
			}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "2d_layout.l"
{ lexstrbuf[strcnt++] = yytext[0]; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "2d_layout.l"
{
			  BEGIN AC;
			  return ACT;
			}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "2d_layout.l"
{
			  BEGIN INITIAL;
			  return ACT_END;
			}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 73 "2d_layout.l"
{
			  BEGIN TR;
			  return TRK;
			}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 77 "2d_layout.l"
{
			  BEGIN AC;
			  return TRK_END;
			}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 81 "2d_layout.l"
return TRK_SET;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 82 "2d_layout.l"
return TRK_WAIT;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 83 "2d_layout.l"
return TRK_MORF;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 84 "2d_layout.l"
{
			  yylval.i_num = 0;
			  return TRK_SPINDIR;
			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 88 "2d_layout.l"
{
			  yylval.i_num = 1;
			  return TRK_SPINDIR;
			}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 92 "2d_layout.l"
{
			  BEGIN TRSTR;
			  strcnt = 0; /* 文字列を最初から */
			}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 96 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\"'; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 97 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\n'; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 98 "2d_layout.l"
{
			  lexstrbuf[strcnt] = 0;
			  yylval.str = &poolbuf[pool(lexstrbuf)];
			  BEGIN TR;
			  return STRING;
			}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 104 "2d_layout.l"
{ lexstrbuf[strcnt++] = yytext[0]; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 106 "2d_layout.l"
{
			  BEGIN ACSTR;
			  strcnt = 0; /* 文字列を最初から */
			}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 110 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\"'; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 111 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\n'; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 112 "2d_layout.l"
{
			  lexstrbuf[strcnt] = 0;
			  yylval.str = &poolbuf[pool(lexstrbuf)];
			  BEGIN AC;
			  return STRING;
			}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 118 "2d_layout.l"
{ lexstrbuf[strcnt++] = yytext[0]; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 120 "2d_layout.l"
{
			  num_line++;
			  BEGIN INITIAL;
			  return NL;
			}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 125 "2d_layout.l"
{
			  yylval.spr_id = SP_EMPTY;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 129 "2d_layout.l"
{
			  yylval.spr_id = SP_POINT;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 133 "2d_layout.l"
{
			  yylval.spr_id = SP_LINE;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 137 "2d_layout.l"
{
			  yylval.spr_id = SP_LINESTRIP;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 141 "2d_layout.l"
{
			  yylval.spr_id = SP_LINESTRIP;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 145 "2d_layout.l"
{
			  yylval.spr_id = SP_BOX;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 149 "2d_layout.l"
{
			  yylval.spr_id = SP_SPRITE;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 153 "2d_layout.l"
{
			  yylval.spr_id = SP_ZOOM;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 157 "2d_layout.l"
{
			  yylval.spr_id = SP_SPIN;
			  DBG("SPIN!!\n");
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 162 "2d_layout.l"
return OBJ_VERTEX;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 163 "2d_layout.l"
return OBJ_PARENT;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 164 "2d_layout.l"
{
			  BEGIN DEFSTR;
			  strcnt = 0; /* 文字列を最初から */
			}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 168 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\"'; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 169 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\n'; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 170 "2d_layout.l"
{
			  lexstrbuf[strcnt] = 0;
			  yylval.str = &poolbuf[pool(lexstrbuf)];
			  BEGIN DEF;
			  return STRING;
			}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 176 "2d_layout.l"
{
			  DBG("str: %c\n", yytext[0]);
			  lexstrbuf[strcnt++] = yytext[0];
			}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 180 "2d_layout.l"
{
			  BEGIN STSTR;
			  strcnt = 0;
			}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 184 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\"'; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 185 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\n'; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 186 "2d_layout.l"
{
			  lexstrbuf[strcnt] = 0;
			  yylval.str = &poolbuf[pool(lexstrbuf)];
			  BEGIN ST;
			  return STRING;
			}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 192 "2d_layout.l"
{ lexstrbuf[strcnt++] = yytext[0]; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 194 "2d_layout.l"
{
			  BEGIN INITIAL;
			  return STAT_END;
			}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 199 "2d_layout.l"
{
			  BEGIN MODE;
			  return STAT_MODE;
			}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 204 "2d_layout.l"
{
			  BEGIN ST;
			  return STAT_MODE_END;
			}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 209 "2d_layout.l"
return MODE_TEX;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 210 "2d_layout.l"
return MODE_VERTEX;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 211 "2d_layout.l"
return MODE_SIZE;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 212 "2d_layout.l"
return MODE_CENTER;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 213 "2d_layout.l"
return MODE_ANGLE;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 214 "2d_layout.l"
return MODE_UV;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 215 "2d_layout.l"
return MODE_UVSIZE;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 216 "2d_layout.l"
return MODE_TEXOFF;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 217 "2d_layout.l"
return MODE_COLOR;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 218 "2d_layout.l"
{
			  BEGIN ALPHA;
			  return MODE_ALPHA;
			}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 222 "2d_layout.l"
{
			  yylval.i_num = 0;
			  return A_COL;
			}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 226 "2d_layout.l"
{
			  yylval.i_num = 1;
			  return A_COL;
			}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 230 "2d_layout.l"
{
			  yylval.i_num = 2;
			  return A_COL;
			}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 234 "2d_layout.l"
{
			  yylval.i_num = 0;
			  return A_ALP;
			}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 238 "2d_layout.l"
{
			  yylval.i_num = 1;
			  return A_ALP;
			}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 242 "2d_layout.l"
{
			  yylval.i_num = 2;
			  return A_ALP;
			}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 246 "2d_layout.l"
{
			  num_line++;
			  BEGIN MODE;
			  return NL;
			}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 252 "2d_layout.l"
return MODE_PRI;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 253 "2d_layout.l"
return MODE_MAGNI;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 254 "2d_layout.l"
return MODE_HIDE;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 255 "2d_layout.l"
return MODE_SHOW;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 256 "2d_layout.l"
{
			  BEGIN MDSTR;
			  strcnt = 0;
			  DBG("mode string\n");
			}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 261 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\"'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 262 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\n'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 263 "2d_layout.l"
{
			  lexstrbuf[strcnt] = 0;
			  yylval.str = &poolbuf[pool(lexstrbuf)];
			  BEGIN MODE;
			  DBG("mode string end\n");
			  return STRING;
			}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 270 "2d_layout.l"
{ lexstrbuf[strcnt++] = yytext[0]; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 272 "2d_layout.l"
{
				  num_line++;
				  return NL;
				}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 276 "2d_layout.l"
return OP_ADD;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 277 "2d_layout.l"
{ DBG("----\n"); return OP_SUB; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 278 "2d_layout.l"
return OP_MUL;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 279 "2d_layout.l"
return OP_DIV;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 280 "2d_layout.l"
return OP_LP;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 281 "2d_layout.l"
return OP_RP;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 282 "2d_layout.l"
return OP_CUM;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 283 "2d_layout.l"
return OP_EXC;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 284 "2d_layout.l"
return OP_LBC;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 285 "2d_layout.l"
return OP_RBC;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 286 "2d_layout.l"
{
			  DBG("FLOAT\n");
			  yylval.f_num = atof(yytext);
			  return FLOAT;
			}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 291 "2d_layout.l"
;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 292 "2d_layout.l"
;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 294 "2d_layout.l"
ECHO;
	YY_BREAK
#line 1675 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DEF):
case YY_STATE_EOF(DEFSTR):
case YY_STATE_EOF(TRI):
case YY_STATE_EOF(TRISTR):
case YY_STATE_EOF(ST):
case YY_STATE_EOF(STSTR):
case YY_STATE_EOF(MODE):
case YY_STATE_EOF(MDSTR):
case YY_STATE_EOF(ALPHA):
case YY_STATE_EOF(AC):
case YY_STATE_EOF(ACSTR):
case YY_STATE_EOF(TR):
case YY_STATE_EOF(TRSTR):
case YY_STATE_EOF(MORF):
case YY_STATE_EOF(COMM):
case YY_STATE_EOF(COMM_DEF):
case YY_STATE_EOF(COMM_TRI):
case YY_STATE_EOF(COMM_ST):
case YY_STATE_EOF(COMM_MD):
case YY_STATE_EOF(COMM_ALP):
case YY_STATE_EOF(COMM_AC):
case YY_STATE_EOF(COMM_TR):
case YY_STATE_EOF(COMM_MF):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 407 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 407 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 406);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 294 "2d_layout.l"

