#
# Makefile for MGS2 Sub Module
#	各ソースがおかれたディレクトリ用 makefile
#
# 2000/06/16 Y.Korekado
# $Id: makefile,v 1.16 2002/08/08 13:05:30 usr01749 Exp $
#

# ベースディレクトリ
BASEDIR = ../../..

# ライブラリ名

LIBNAME = korekado.a

# オブジェクトリスト
OBJECTS = item.o asitest.o asiato.o windnois.o bgmfader.o db_tex.o moveobj.o strmfadr.o \
			enemem.o namepri.o  vrpitfall.o deadline.o vrcaptur.o dummytrg.o

XOBJECTS = item.obj asitest.obj asiato.obj windnoisx.obj bgmfader.obj db_tex.obj moveobj.obj strmfadr.obj \
			enemem.obj namepri.obj  vrpitfall.obj deadline.obj vrcaptur.obj dummytrg.obj

# ここでのローカルフラグリスト

LOCAL_INCLUDES = ../conv
LOCAL_DEFINES = 
LOCAL_OPTIONS = 

# 設定の実体

include $(BASEDIR)/makefile.sub

# 依存関係のリスト


