/*
	tng_enum.h
	tngdefで使用
	tngthinkはat_enumを共用
	2000/05/16 K.Sigeno
	$Id: tng_enum.h,v 1.1.1.3 2002/11/19 11:49:53 Yoshizawa1 Exp $
*/


/*----- 思考状態 --------------------------------------------------*/
/*通常、危険、回避、守備*/

enum	{
	TH2_TRAVEL,TH2_NOISE,TH2_DANBOWL,TH2_FAINT,TH2_HIT,TH2_ASIATO,
	TH2_GO_TRAVEL,TH2_DISCOVERY,/*7*/
	TH2_CHASE, TH2_ATTACK, TH2_MOVE,
	TH2_GO_AVOID, TH2_GO_AVOID2, TH2_SEARCH
} ;
enum	{
	TH3_RETURN_TRAVEL,TH3_GO_NEXT, TH3_POINT_ACTION, TH3_RETURN_ORDER, /*3*/
	TH3_WAIT,TH3_WATCH,TH3_WATCH_M,TH3_LOOKOVER,TH3_NIKITA,
	TH3_ZONETRACE, TH3_DIRECTTRACE,
	TH3_LOOKAROUND,TH3_DANBOWLKERI,TH3_DANBOWLWAIT,/*13*/
	TH3_DISCOVERY_POSE,TH3_DISCOVERY_POSE_M,TH3_DISCOVERY_STAND,
	TH3_DISCOVERY_STAND2,/*17*/
	TH3_ZONE_CHASE_WARP, TH3_ZONE_CHASE,TH3_DIRECT_CHASE,/*20*/
	TH3_ATTACK_HANDGUN,TH3_ATTACK_FAMAS3,TH3_SETUP_GRENADE,
	TH3_ATTACK_GRENADE,TH3_ATTACK_NEAR,TH3_ATTACK_BEAT,/*26*/
	TH3_ATTACK_SETUP,
	TH3_MOVE_LASTPT,TH3_MOVE_LASTPT_WARP,TH3_MOVE_END,/*30*/

	TH3_SEARCH_RANDOM, TH3_SEARCH_STAND, TH3_SEARCH_SNAKE,
	TH3_SEARCH_ZONE,TH3_ZONE_RETURN,/* 35 */
	TH3_DIRECT_RETURN,TH3_SAFEZONE_CHASE,TH3_WAIT_SAFE,
	TH3_SIDE_OUT,TH3_ATTACK_RELOAD, /*40*/
	TH3_SIDE_IN,TH3_WAIT_CHASE,TH3_ATTACK_SIEGE,
	TH3_TURN_CHASE,TH3_SIDE_MOVE, /* 45 */
	TH3_WAIT_LOWSAFE,TH3_GOSIGN,TH3_DANGER,TH3_ROLL_OUT,
	TH3_SIDE_STEP, /*50*/
	TH3_MUKA_ZONE,TH3_MUKA_DIRECT,
	TH3_ESC_ZONECHASE,TH3_BEHIND,TH3_ZONE_POS, /*55*/
	TH3_DIRECT_POS,TH3_SHL_BREAK,
	TH3_ATTACK_EASY,TH3_ATTACK_STOMP, 
	TH3_CHASE_BEYOND,TH3_SAFEDIRECT_CHASE, /*61*/
	TH3_ATTACK_GRD,TH3_NSIGHT_ON,TH3_ATTACK_GRD_HIGH ,
	TH3_DIRECT_CHASE_JUMP,TH3_START_JUMP
} ;

