#
# Makefile for MGS2 Sub Module
#	各ソースがおかれたディレクトリ用 makefile
#
# 2000/04/19 Y.Korekado
# $Id: makefile,v 1.7 2002/05/09 12:40:11 usr01749 Exp $
#

# ベースディレクトリ
BASEDIR = ../../..

# ライブラリ名

LIBNAME = korekado.a

# オブジェクトリスト
OBJECTS = putatach.o putatach_scn.o c4_effct.o c4manage.o vrspot.o
XOBJECTS = putatach.obj putatach_scn.obj c4_effct.obj c4manage.obj vrspot.obj

# ここでのローカルフラグリスト

LOCAL_INCLUDES = ../conv
LOCAL_DEFINES = 
LOCAL_OPTIONS = 

# 設定の実体

include $(BASEDIR)/makefile.sub

# 依存関係のリスト

