#
# Makefile for MGS2 Sub Module
#	各ソースがおかれたディレクトリ用 makefile
#
# 2002/03/12 S.Yamashita
# $Id: makefile,v 1.1.1.3 2002/11/19 11:51:50 Yoshizawa1 Exp $
#

# ベースディレクトリ
BASEDIR = ../../..

# ライブラリ名
LIBNAME = yamashita.a

# オブジェクトリスト
OBJECTS = floor_marker.o wall_marker.o

XOBJECTS = floor_marker.obj wall_marker.obj

# ここでのローカルフラグリスト
LOCAL_INCLUDES = 
LOCAL_DEFINES = 
LOCAL_OPTIONS = 

# 設定の実体
include $(BASEDIR)/makefile.sub
