#
# Makefile for MGS2 Sub Module
#	各ソースがおかれたディレクトリ用 makefile
#

# ベースディレクトリ
BASEDIR = ../../..

# ライブラリ名

LIBNAME = skoba.a
# オブジェクトリスト
OBJECTS = TestBox.o etc.o c4_ice.o c4_eff.o c4_comdl.o c4_ice_mng.o \
		  irs_mng.o irs_lamp.o newirs.o Senser.o test_sprite.o \
		  sk_printf.o sensor_lamp.o

XOBJECTS = TestBox.obj etc.obj c4_ice.obj c4_eff.obj c4_comdl.obj c4_ice_mng.obj \
		  irs_mng.obj irs_lamp.obj newirs.obj Senser.obj \
		  sensor_lamp.obj test_sprite.obj \
		  sk_printf.obj 

# ここでのローカルフラグリスト

LOCAL_INCLUDES =
LOCAL_DEFINES = 
LOCAL_OPTIONS =

# 設定の実体

include $(BASEDIR)/makefile.sub

# 依存関係のリスト


