/* SCE CONFIDENTIAL
* PlayStation(R)Edge 1.2.0
* Copyright (C) 2007 Sony Computer Entertainment Inc.
* All Rights Reserved.
*/

void main( 	
		in float2 in_uv : TEXCOORD0
	,	out half4 out_value : COLOR0 
	)
{
	bool2 evens = ( frac( in_uv ) < 0.5.xx );
	bool check = evens.y ? evens.x : !evens.x;
	
	half4 a = half4( 0.3, 0.3, 0.3, 1.0 );
	half4 b = half4( 0.4, 0.4, 0.4, 1.0 );
	out_value = check ? a : b;
}

