/* SCE CONFIDENTIAL
* PlayStation(R)Edge 1.2.0
* Copyright (C) 2007 Sony Computer Entertainment Inc.
* All Rights Reserved.
*/

void main(	
		in float4 in_coord : ATTR0
	,	uniform float4 scaleOffset : register( c0 )
	,	uniform float4 uvRotation : register( c1 )
	,	out float4 out_position : POSITION
	,	out float2 out_uv : TEXCOORD0 )
{
	out_position.xy = in_coord.xy*scaleOffset.xy + scaleOffset.zw;
	out_position.zw = in_coord.zw;

	float2 rotated = in_coord.xx*uvRotation.xy + in_coord.yy*uvRotation.zw;
	out_uv.xy = rotated*float2(0.5, -0.5) + 0.5.xx;
}

