#
# Makefile for MGS2 Sub Module
#	各ソースがおかれたディレクトリ用 makefile
#

# ベースディレクトリ
BASEDIR = ../../..

# ライブラリ名

LIBNAME = shibata.a

# オブジェクトリスト
OBJECTS = piyori.o piyori_anes.o control_headmark.o zzz.o control_headmark2.o control_headmark3.o

XOBJECTS = piyori.obj piyori_anes.obj control_headmark.obj zzz.obj control_headmark2.obj control_headmark3.obj

# ここでのローカルフラグリスト

LOCAL_INCLUDES =
LOCAL_DEFINES = 
LOCAL_OPTIONS =

# 設定の実体

include $(BASEDIR)/makefile.sub

# 依存関係のリスト


