#
# Makefile for MGS2 Sub Module
#	各ソースがおかれたディレクトリ用 makefile
#
#	1999/07/07 K.Takabe
#	$Id: makefile,v 1.1 2002/11/04 04:06:37 Yoshizawa1 Exp $
#

# ベースディレクトリ
BASEDIR = ../..

# ライブラリ名

LIBNAME = libwbc.a

# オブジェクトリスト
OBJECTS =	
XOBJECTS =  
WOBJECTS = amextra.obj amfilter.obj amvideo.obj combase.obj cprop.obj ctlutil.obj ddmm.obj dllentry.obj dllsetup.obj mtype.obj outputq.obj pstream.obj pullpin.obj refclock.obj renbase.obj schedule.obj seekpt.obj source.obj strmctl.obj sysclock.obj transfrm.obj transip.obj videoctl.obj vtrans.obj winctrl.obj winutil.obj wxdebug.obj wxlist.obj wxutil.obj

# ここでのローカルフラグリスト

LOCAL_INCLUDES =
LOCAL_DEFINES = 
LOCAL_OPTIONS = 

# 設定の実体

# ifeq ($(MGS2_XBOX),1)
# all : $(XSHADE_OBJS)
# lib : $(XSHADE_OBJS)
# endif

include $(BASEDIR)/makefile.sub

# 依存関係のリスト

