/*
	atavoid.h
	攻撃兵回避モードヘッダ

	1997/07/26 Y.Korekado
	$Id: atavoid.h,v 1.1.1.3 2002/11/19 11:43:58 Yoshizawa1 Exp $
	
*/
#ifndef __WATCHER___
#define	__WATCHER___ 1

/*----- 思考状態 --------------------------------------------------*/
enum	{
	TH1_NORMAL, TH1_ALERT, TH1_AVOID
} ;
enum	{
	TH2_TRAVEL,TH2_NOISE,TH2_DANBOWL,TH2_FAINT,TH2_HIT,TH2_ASIATO,TH2_GO_TRAVEL,TH2_DISCOVERY,/*7*/
	TH2_CHASE, TH2_ATTACK, TH2_MOVE,
	TH2_GO_AVOID, TH2_GO_AVOID2, TH2_SEARCH,
	TH2_READY, TH2_DYNAMIC_ENTRY, TH2_READY_CLEARING, TH2_CLEARING, TH2_CLE_COMP
} ;
enum	{
	TH3_RETURN_TRAVEL,TH3_GO_NEXT, TH3_POINT_ACTION, TH3_RETURN_ORDER, /*3*/
	TH3_WAIT,TH3_WATCH,TH3_WATCH_M,TH3_LOOKOVER,TH3_NIKITA,TH3_ZONETRACE, TH3_DIRECTTRACE, TH3_LOOKAROUND,/*11*/
	TH3_DANBOWLKERI,TH3_DANBOWLWAIT,/*13*/

	TH3_DISCOVERY_POSE,TH3_DISCOVERY_POSE_M,TH3_DISCOVERY_STAND,TH3_DISCOVERY_STAND2,/*17*/
	TH3_ZONE_CHASE_WARP, TH3_ZONE_CHASE,TH3_DIRECT_CHASE,/*20*/
	TH3_ATTACK_HANDGUN,TH3_ATTACK_MGUN,TH3_SETUP_GRENADE,TH3_ATTACK_GRENADE,TH3_ATTACK_NEAR,TH3_ATTACK_BEAT,/*26*/
	TH3_ATTACK_SETUP,TH3_ATTACK_RELOAD,
	TH3_MOVE_LASTPT,TH3_MOVE_LASTPT_WARP,TH3_MOVE_END,/*31*/

	TH3_SEARCH_RANDOM, TH3_SEARCH_STAND, TH3_SEARCH_SNAKE, TH3_SEARCH_ZONE,
	TH3_ZONE_RETURN,TH3_DIRECT_RETURN
} ;

/*-----	定数定義	-----*/

	/*アクションパッド */
enum {
	SP_NONE,
	SP_DOWNBACK,
	SP_DISCOVERY,	/* 発見ポーズ */
	SP_READYGUN,	/* 銃構える */
	SP_CAUT_STAND,	/* 警戒立ち */
	SP_MGUN_SHOT,	/* マシンガン撃つ */
	SP_RELOAD,		/* リロード */
	SP_CLE_GOSIGN,	/* 突撃合図 */
	SP_CLE_PEEP_L,	/* 左覗き込み */
	SP_CLE_PEEP_R,	/* 右覗き込み */

	/* 注！！移動変更アクションパッドはこれ以上の値にすること */
	SP_MV_WALK,		/* 歩き */
	SP_MV_RUN,		/* 走り */
	SP_MV_CAUT_WALK,/* 警戒歩き */
	SP_MV_CAUT_RUN,	/* 警戒走り */
	SP_MV_SIDE_L,	/* 左横移動 */
	SP_MV_SIDE_R,	/* 右横移動 */
	SP_MV_BACK		/* バック */
} ;

#endif
