//----------------------------------------------------------------------------
//BP - added stdafx.h to get precompiled MGS_SysCommon.h in Windows
#include "stdafx.h"
//BP
//----------------------------------------------------------------------------
/*
   標準関数処理

   if と return

	1999/07/08 K.Uehara
	$Id: basic.c,v 1.1.1.3 2002/11/19 11:42:41 Yoshizawa1 Exp $
*/

#include	<stdio.h>
#include	<stdlib.h>
#include	<sys/types.h>
#include	<string.h>
#include	<ctype.h>

#include	"libgcl.h"

void *GCL_Parse_if( char *top )
{
	int type, res;
	char *p, *block;

	p = top;

EXEC_IF:
	/* 式の解釈 */
	p = GCL_GetNextValue( p, &type, &res );

EXEC_ELSE:
	p = GCL_GetNextValue( p, &type, ( int * )&block );
	GCL_ASSERT( type == GCL_BLOCK );

	if( res ){
		return block;
	} else {
		p = GCL_GetNextValue( p, &type, &res );
		if( p != NULL ){
			GCL_ASSERT( GCL_TAG( type ) == GCL_OPTION );
			type = type >> 16;
			p = ( char * )res;
			if( type == 'e' ){
				/* else */
				res = 1;
				goto EXEC_ELSE;
			} else if( type == 'i' ){
				/* else if */
				goto EXEC_IF;
			} else {
				GCL_ASSERT( 0 );
			}
		}
	}
	return NULL;
}

static int command_if( char *top )
{
	char *block;

	block = GCL_Parse_if( top );
	if( block != NULL ){
		return GCL_ExecBlockBody( block, NULL, 0 );
	} else {
		return GCL_OK;
	}
}

static int command_switch( char *top )
{
	char *p = top;
	void *block = NULL;
	int type, value;

	/* 式の解釈 */
	p = GCL_GetNextValue( p, &type, &value );
	GCL_SetArgTop( p );

	for( ;; ){
		int opt;
		opt = GCL_GetNextOption();
		if( opt == 0 ){
			return GCL_OK;
		}
		if( opt == 'c' ){
			int c;
			c = GCL_GetNextInt();
			if( c == value ){
				GCL_GetNextValue( GCL_NextStr(), &type, ( int * )&block );
				break;
			}
		} else if( opt == 'd' ){
			GCL_GetNextValue( GCL_NextStr(), &type, ( int * )&block );
			break;
		}
	}
	return GCL_ExecBlockBody( block, NULL, 0 );
}


int GCL_Command_eval( char *top )
{
	char *p;
	int type, res;

	p = top;

	p = GCL_GetNextValue( p, &type, &res );
//printf( "%X\n", p );
//	ASSERT( type == GCL_EXPR );

	/* この時点で、p には式の次のアドレスが入っている */

	GCL_Status = res;

	return GCL_OK;
}

int GCL_Command_return( char *top )
{
	if( GCL_NextStr() != NULL ){
		GCL_Status = GCL_GetNextInt();
//printf( "return %d\n", GCL_Status );
	} else {
		GCL_Status = 0;
	}
	return GCL_RETURN;
}

int GCL_Command_print( char *top )
{

#if GCL_ENABLE_PRINT_COMMAND
   printf( "print:" );
#endif

	while( top != NULL ){
		int type, value;
		top = GCL_GetNextValue( top, &type, &value );
		if( type == GCL_END ){
			break;
		} 
#if GCL_ENABLE_PRINT_COMMAND
      else if( type == GCL_STRING ){
			printf( "%s ", ( char * )value );
		} else if( type == GCL_STRRES ){
			unsigned char *p;
			p = ( char * )value;
			for( ; *p != '\0'; p++ ){
				printf( "%02X ", *p );
			}
		} else {
			printf( "%d(%X) ", value, value );
		}
#endif
   }
#if GCL_ENABLE_PRINT_COMMAND
	printf( "\n" );
#endif
    return GCL_OK ;
}

int GCL_Command_call( char *top )
{
	int argbuf[ GCL_PROC_MAX_ARGS ];
	int i, id;
	GCL_ARGS arg;
	unsigned char *p;

	/* 先頭は ID */
	id = GCL_GetNextInt();
	p = GCL_NextStr();
	for( i = 0; ; i++ ){
		int type, value;

		p = GCL_GetNextValue( p, &type, &value );
		if( type == GCL_END ) break;
		if( i >= GCL_PROC_MAX_ARGS ){
			printf( "TOO MANY ARGS PROC %d\n", GCL_PROC_MAX_ARGS );
			HANGUP();
		}
		argbuf[ i ] = value;
	}
	arg.argc = i;
	arg.argv = argbuf;

	return GCL_ExecProc( id, &arg );
}

#if 1 //BP_TODO : These id's were generated by running the perl script over the file.

static GCL_COMMANDLIST commlist[] = {
   { 3462,     command_if },
   { 10902965, command_switch },
   { 3433612,   GCL_Command_eval },
   { 3346924,   GCL_Command_call },
   { 9167768, GCL_Command_return },
   { 3846715,  GCL_Command_print },
};

#else

static GCL_COMMANDLIST commlist[] = {
	{ $$STRID( "if" )$$,     command_if },
	{ $$STRID( "switch" )$$, command_switch },
	{ $$STRID( "eval" )$$,   GCL_Command_eval },
	{ $$STRID( "call" )$$,   GCL_Command_call },
	{ $$STRID( "return" )$$, GCL_Command_return },
	{ $$STRID( "print" )$$,  GCL_Command_print },
};

#endif

static GCL_COMMANDDEF builtin_commands = GCL_COMMANDS( commlist );

void GCL_InitBasicCommands( void )
{
	GCL_AddCommMulti( &builtin_commands );
}
