#
# Makefile for MGS2 Sub Module
#	各ソースがおかれたディレクトリ用 makefile
#
# 1999/12/26 N.Tanaka
# $Id: makefile,v 1.14 2002/02/01 04:43:47 usr01475 Exp $
#

# ベースディレクトリ
BASEDIR = ../../..

# ライブラリ名

LIBNAME = nobu.a

# オブジェクトリスト
OBJECTS =	piyori.o \
			piyoanes.o \
			zzz.o \
			c_light.o \
			fade_io.o \
			d_blood.o \
			d_plasma_line.o \
			eneequip.o \
			body_sdw.o \
			crtrg.o \
			n_focus.o \
			f_focus.o \
			put_stanime.o \
			handanim.o \
			e3_fanim.o \
			d_vol_shadow.o \
			d_plasma_poly.o \
			oozeblod.o \
			rope_called.o \
			waving_cloth.o \
			rope_called2.o \
			mm_orga.o \
			smk_blur.o \
			body_sph.o \
			raincoat.o \
			foot_shadow.o \
			drop_shadow.o \
			attachment.o \
			d_inter_poly.o \
			pt_attch.o \
			ft_splash.o \
			saa_smoke.o \
			vanime_buller.o \
			demo_bullet.o \
			facedemo.o

# ここでのローカルフラグリスト

LOCAL_INCLUDES =
LOCAL_DEFINES = 
LOCAL_OPTIONS = 

# 設定の実体

include $(BASEDIR)/makefile.sub

# 依存関係のリスト

piyori.o : piyori.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
piyoanes.o : piyoanes.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
zzz.o : zzz.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
c_light.o : c_light.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
fade_io.o : fade_io.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
d_blood.o : d_blood.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
d_plasma_line.o : d_plasma_line.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
d_body_plasma_dot.o : d_body_plasma_dot.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
eneequip.o : eneequip.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
body_sdw.o : body_sdw.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
crtrg.o : crtrg.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
n_focus.o : n_focus.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
f_focus.o : f_focus.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
put_stanime.o : put_stanime.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
handanim.o : handanim.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
e3_fanim.o : e3_fanim.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
d_vol_shadow.o : d_vol_shadow.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
d_plasma_poly.o : d_plasma_poly.c ../demo/demo_.h ../demo/demo.h ../demo/DE2Struct.h
