#
# Makefile for UVMap 
#	
#	Tue Nov 16 07:45:11 JST 1999
#	T.Morita
#
#	$Id: makefile,v 1.1 2002/04/16 03:45:36 usr04098 Exp $
#
TARGET = makekls

ifeq ($(MGS2_WIN32),1)
INSTDIR = /u/develop/mj001b/exports/tools/bin/mgs2xbox
else
INSTDIR = /u/develop/mj001b/tools/bin/linux
endif

install:
	cp $(TARGET) $(INSTDIR)

