#
# Makefile for MGS2 Sub Module
#	各ソースがおかれたディレクトリ用 makefile
#
# 1999/07/08 K.Uehara
# $Id: makefile,v 1.1.1.3 2002/11/19 11:51:29 Yoshizawa1 Exp $
#

# ベースディレクトリ
BASEDIR = ../../..

# ライブラリ名

LIBNAME = takabe.a

# オブジェクトリスト
OBJECTS = m_weight.o box_view.o comdltst.o \
	tst_prm2.o tst_evm.o tst_dmpk.o tst_ptch.o put_mdl.o tst_obj.o tst_obj2.o
NO_USE = tst_ik.o anmtex.o

XOBJECTS = box_view.obj

# 実験用（既に未使用になったもの）
# takabe.o m_print.o 

# ここでのローカルフラグリスト

LOCAL_INCLUDES =
LOCAL_DEFINES = 
LOCAL_OPTIONS = 

# 設定の実体

include $(BASEDIR)/makefile.sub

# 依存関係のリスト


