using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.IO;

namespace GenerateLinkvarSwapTable
{
    class Program
    {
        const string MGS2LinkvarH = @"C:\dev\drowe_DROWE-PC\cp4a-dev\MGS2\mgs2x\source\include\linkvar.h";
        const string MGS3LinkvarH = @"C:\dev\drowe_DROWE-PC\cp4a-dev\MGS3\source\include\linkvar.h";
        const string LinkvarOutFile = @"Transfarring_EndianSwapList.cpp";
        const string EndianSwapFunc1 = @"0";
        const string EndianSwapFunc2 = @"BP_LE_Swap2Bytes";
        const string EndianSwapFunc4 = @"BP_LE_Swap4Bytes";
        const string EndianSwapFunc8 = @"BP_LE_Swap8Bytes";
        static List<string> WriteArray;

        struct NameAndBytes
        {
            public NameAndBytes(string n, int b)
            {
                name = n;
                bytes = b;
            }

            public string name;
            public int bytes;
        }

        // Special case endian swapping functions, for structs and variable data types
        static Dictionary<string, string> SwapOverrideMap;

        static void Main(string[] args)
        {
            WriteArray = new List<string>();
            WriteArray.Add(@"#include ""Engine/Stdafx.h""");
            WriteArray.Add(@"#include ""BP_EndianSupport.h""");
            WriteArray.Add(@"#include ""Transfarring_EndianSwapList.h""");
            WriteArray.Add("");

            // Write MGS2 section
            SwapOverrideMap = new Dictionary<string, string>();
            SwapOverrideMap.Add(@"ENEMEM_EneMem", @"LE_SwapEnemem");

            WriteLinkvarSwapTable(MGS2LinkvarH, "2");

            // Write MGS3 section
            SwapOverrideMap.Clear();
            SwapOverrideMap.Add(@"ENEMEM_EneMem", @"LE_SwapEnemem");
            SwapOverrideMap.Add(@"GM_PlayerWoundHist", @"LE_SwapPlayerWoundHistory");
            SwapOverrideMap.Add(@"GM_TntStorage", @"LE_SwapTntStorage");
            SwapOverrideMap.Add(@"GM_RatTrapStorage", @"LE_SwapRatTrapStorage");
            SwapOverrideMap.Add(@"GM_EventSaveData", @"LE_SwapEventSaveData");
            WriteLinkvarSwapTable(MGS3LinkvarH, "3");

            // Write final CPP file
            string[] WriteLines = WriteArray.ToArray();
            File.WriteAllLines(LinkvarOutFile, WriteLines);
        }

        static void WriteLinkvarSwapTable(string LinkvarHFile, string MGSVersion)
        {
            List<NameAndBytes> BytesArray = new List<NameAndBytes>();

            string[] InFileLines = File.ReadAllLines(LinkvarHFile);

            int LinkvarBufferSize = 0;
            int LastLinkvarOffset = 0;
            int LastLinkVarBytes = 0;
            string LastLinkVarName = "";

            WriteArray.Add(@"#if MGS_VERSION == " + MGSVersion);
            WriteArray.Add(@"/* AUTOMATICALLY GENERATED BY GenerateLinkvarSwapTable.exe */");
            WriteArray.Add(" ");
            /*WriteArray.Add(@"// Forward declarations of special swap functions");
            foreach (KeyValuePair<string, string> kvp in SwapOverrideMap)
            {
                WriteArray.Add(@"void " + kvp.Value + @"(void*, const void*);");
            }
            WriteArray.Add(" ");*/
            WriteArray.Add("const LinkvarEndianSwapFunc kSwapTable[] =");
            WriteArray.Add("{");

            int numSwapFuncs = 0;
            bool firstFound = false;

            for (int i = 0; i < InFileLines.Length; i++)
            {
                string s = InFileLines[i];

                // Only interested in lines where something is defined
                if (!s.Contains(@"#define"))
                {
                    continue;
                }

                // This should be the final step
                if (s.Contains("MAX_LINKVARBUF"))
                {
                    string[] bufferSize = Regex.Split(s, @"\D+");
                    foreach (string b in bufferSize)
                    {
                        // There should only be one integer on this line
                        if (!string.IsNullOrEmpty(b))
                        {
                            // Write the final linkvar swap
                            LinkvarBufferSize = int.Parse(b);
                            int FinalLinkvarSize = LinkvarBufferSize - LastLinkvarOffset;
                            WriteSwapLine(FinalLinkvarSize, FinalLinkvarSize / LastLinkVarBytes, WriteArray, LastLinkVarName, BytesArray, ref numSwapFuncs);
                            break;
                        }
                    }
                    break;
                }

                // Match patterns with an underscore to find the name of the linkvar
                Match match = Regex.Match(s, @"\b\s.*_.*\t");
                if (match == null)
                {
                    continue;
                }

                string LinkVarName = match.Value.Trim('\t', ' '); // Easier than actually learning this regular expression stuff, lmao

                // Match patterns with a char, short, or int
                match = Regex.Match(s, @"short |char |int");

                // Scroll to the end of the matches in case we got a false positive in the linkvar name
                string LinkVarType = "";
                while (match.Value.Length > 0)
                {
                    LinkVarType = match.Value.Trim();
                    match = match.NextMatch();
                }

                // Figure out how many bytes this type is
                int LinkVarBytes = 0;
                switch (LinkVarType)
                {
                    case "char":
                        LinkVarBytes = 1;
                        break;
                    case "short":
                        LinkVarBytes = 2;
                        break;
                    case "int":
                        LinkVarBytes = 4;
                        break;
                }

                // Make sure we got a good value
                System.Diagnostics.Debug.Assert(LinkVarBytes > 0 && LinkVarBytes <= 4);

                // Split into a list of integers; the final one is the offset into the array
                string[] numbers = Regex.Split(s, @"\D+");

                // For each number we found, add it to the list; sometimes numbers appear in the linkvar name, we just want the last number
                List<int> numberList = new List<int>();
                foreach (string n in numbers)
                {
                    if (!string.IsNullOrEmpty(n))
                    {
                        numberList.Add(int.Parse(n));
                    }
                }

                System.Diagnostics.Debug.Assert(numberList.Count > 0);

                int CurrentLinkvarOffset = numberList[numberList.Count - 1];
                if (firstFound)
                {
                    // Subtract the current offset from the last offsize to find the size of the data
                    int LastLinkvarSize = CurrentLinkvarOffset - LastLinkvarOffset;

                    System.Diagnostics.Debug.Assert(LastLinkvarSize % LastLinkVarBytes == 0);

                    // Handle arrays of data
                    WriteSwapLine(LastLinkVarBytes, LastLinkvarSize / LastLinkVarBytes, WriteArray, LastLinkVarName, BytesArray, ref numSwapFuncs);

                    LastLinkvarOffset = CurrentLinkvarOffset;
                }
                else
                {
                    firstFound = true;
                }

                LastLinkVarName = LinkVarName;
                LastLinkVarBytes = LinkVarBytes;
            }

            WriteArray.Add("};");
            WriteArray.Add(" ");

            System.Diagnostics.Debug.Assert(numSwapFuncs == BytesArray.Count);
            
            // Write out bytes array
            WriteArray.Add(@"const int kBytesPerSwap[] =");
            WriteArray.Add(@"{");
            for (int i = 0; i < BytesArray.Count; i++)
            {
                WriteArray.Add("  " + BytesArray[i].bytes.ToString() + ", // " + BytesArray[i].name);
            }
            WriteArray.Add(@"};");

            WriteArray.Add(" ");
            WriteArray.Add("const int kNumSwaps = " + numSwapFuncs.ToString() + ";");
            WriteArray.Add(" ");

            // Write function stubs
            /*foreach (KeyValuePair<string, string> kvp in SwapOverrideMap)
            {
                WriteArray.Add(@"void " + kvp.Value + @"(void* dst, const void* src)");
                WriteArray.Add(@"{");
                WriteArray.Add(@"}");
                WriteArray.Add(@" ");
            }*/

            WriteArray.Add(@"#endif");
            WriteArray.Add(@" ");
        }

        static void WriteSwapLine(int size, int num, List<string> WriteArray, string name, List<NameAndBytes> BytesArray, ref int NumSwapFuncs)
        {
            string swapFunc = "";

            int bytes = 0;
            if (SwapOverrideMap.TryGetValue(name, out swapFunc))
            {
                bytes = size * num;
                WriteArray.Add("   " + swapFunc + @",        // " + name + @" (" + bytes.ToString() + @" bytes)");
                BytesArray.Add(new NameAndBytes(name, bytes));
                NumSwapFuncs++;
                return;
            }
            
            switch (size)
            {
                default:
                    System.Diagnostics.Debug.Assert(false, "Unknown size");
                    break;
                case 1:
                    // Byte
                    swapFunc = EndianSwapFunc1;
                    break;
                case 2:
                    // Short
                    swapFunc = EndianSwapFunc2;
                    break;
                case 4:
                    // Int/Float
                    swapFunc = EndianSwapFunc4;
                    break;
                case 8:
                    // Long/Double
                    swapFunc = EndianSwapFunc8;
                    break;
            }

            // Handle arrays
            bytes = size;
            NameAndBytes nb = new NameAndBytes(name, bytes);
            for (int i = 0; i < num; i++)
            {
                WriteArray.Add("   " + swapFunc + @",        // " + name + @" (" + bytes.ToString() + @" bytes)");
                BytesArray.Add(nb);
                NumSwapFuncs++;
            }
        }
    }
}
