#
# Makefile for MGS2 Sub Module
#	各ソースがおかれたディレクトリ用 makefile
#
# 1999/07/08 K.Uehara
# $Id: makefile,v 1.1.1.3 2002/11/19 11:51:58 Yoshizawa1 Exp $
#

# ベースディレクトリ
BASEDIR = ../../..

# ライブラリ名

LIBNAME = yano.a

# オブジェクトリスト
OBJECTS = 	kan_splash.o kan_splash2.o kan_splash3.o goruruko.o duct_sight.o duct_sight2.o \
		glass_mist.o glass_mist2.o \
		vr_gmover.o vr_clear_eft2.o

XOBJECTS = 	kan_splash.obj kan_splash2.obj kan_splash3.obj goruruko.obj duct_sight.obj duct_sight2.obj \
		glass_mist.obj glass_mist2.obj \
		vr_gmover.obj vr_clear_eft2.obj


#call_goru.obj


# ここでのローカルフラグリスト

LOCAL_INCLUDES = 
LOCAL_DEFINES = 
LOCAL_OPTIONS = 

# 設定の実体
include $(BASEDIR)/makefile.sub
