/* SCE CONFIDENTIAL
 * PlayStation(R)Edge 1.2.0
 * Copyright (C) 2009 Sony Computer Entertainment Inc.
 * All Rights Reserved.
 */
 
 
void main
	(
		in float2 in_uv : TEXCOORD0,
		in float3 position : WPOS,
		uniform sampler2D sourceImage : TEXUNIT0,
		uniform sampler2D bloomImage : TEXUNIT1,
		uniform half bloomStrength, 
		out half4 out_color : COLOR
	)
{
	half4 base = h4tex2D( sourceImage, in_uv );
	half3 bloom = h3tex2D( bloomImage, in_uv );
	
	out_color.rgb = base.rgb * base.a + bloom.rgb * bloomStrength.xxx;
	out_color.a = base.a;
}
