/* SCE CONFIDENTIAL
 * PlayStation(R)Edge 1.2.0
 * Copyright (C) 2009 Sony Computer Entertainment Inc.
 * All Rights Reserved.
 */

void main
	(
		in float2 in_uv : TEXCOORD0,
		in float3 position : WPOS,
		uniform sampler2D sourceImage : TEXUNIT0,
		uniform float dx,
		uniform float4 weights,
		out half4 out_color : COLOR
	)
{
	half4 sample = 0.0.xxxx;
	
	sample += h4tex2D( sourceImage, in_uv ) * weights.x;
	sample += h4tex2D( sourceImage, in_uv + float2( 1 * dx, 0) ) * weights.y;
	sample += h4tex2D( sourceImage, in_uv - float2( 1 * dx, 0) ) * weights.y;
	sample += h4tex2D( sourceImage, in_uv + float2( 2 * dx, 0) ) * weights.z;
	sample += h4tex2D( sourceImage, in_uv - float2( 2 * dx, 0) ) * weights.z;
	sample += h4tex2D( sourceImage, in_uv + float2( 3 * dx, 0) ) * weights.w;
	sample += h4tex2D( sourceImage, in_uv - float2( 3 * dx, 0) ) * weights.w;
	
	out_color = sample;
}
