/*
	at_enum.h
	アタッカとコマンダ用 think変数のenum
	1999/09/16 K.Sigeno
	$Id: at_enum.h,v 1.1.1.3 2002/11/19 11:48:59 Yoshizawa1 Exp $
*/


/*----- 思考状態 --------------------------------------------------*/
/*通常、危険、回避、守備*/

enum	{
	TH2_TRAVEL,TH2_NOISE,TH2_DANBOWL,TH2_FAINT,TH2_HIT,TH2_ASIATO,
	TH2_GO_TRAVEL,TH2_DISCOVERY,TH2_CHASE, TH2_ATTACK, /*9*/
	TH2_MOVE,TH2_GO_AVOID, TH2_GO_AVOID2, TH2_SEARCH, /*13*/
	TH2_THREAT,TH2_APPROACH,TH2_INTRUDE,TH2_SYMMETRY,TH2_RESCUE,TH2_PBREAK
} ;
enum	{
	TH3_RETURN_TRAVEL,TH3_GO_NEXT, TH3_POINT_ACTION, TH3_RETURN_ORDER, /*3*/
	TH3_WAIT,TH3_WATCH,TH3_WATCH_M,TH3_LOOKOVER,TH3_NIKITA,
	TH3_ZONETRACE, TH3_DIRECTTRACE,
	TH3_LOOKAROUND,TH3_DANBOWLKERI,TH3_DANBOWLWAIT,/*13*/
	TH3_DISCOVERY_HANG,TH3_DISCOVERY_DEATH,TH3_DISCOVERY_STAND,
	TH3_DISCOVERY_STAND2,/*17*/
	TH3_ZONE_CHASE_WARP, TH3_ZONE_CHASE,TH3_DIRECT_CHASE,/*20*/
	TH3_ATTACK_HANDGUN,TH3_ATTACK_FAMAS3,TH3_SETUP_GRENADE,
	TH3_ATTACK_GRENADE,TH3_ATTACK_NEAR,TH3_ATTACK_BEAT,/*26*/
	TH3_ATTACK_SETUP,
	TH3_MOVE_LASTPT,TH3_MOVE_LASTPT_WARP,TH3_MOVE_END,/*30*/

	TH3_SEARCH_RANDOM, TH3_SEARCH_STAND, TH3_SEARCH_SNAKE,
	TH3_SEARCH_ZONE,TH3_ZONE_RETURN,/* 35 */
	TH3_DIRECT_RETURN,TH3_SAFEZONE_CHASE,TH3_WAIT_SAFE,
	TH3_SIDE_OUT,TH3_ATTACK_RELOAD, /*40*/
	TH3_SIDE_IN,TH3_WAIT_CHASE,TH3_ATTACK_SIEGE,
	TH3_TURN_CHASE,TH3_SIDE_MOVE, /* 45 */
	TH3_WAIT_LOWSAFE,TH3_GOSIGN,TH3_DANGER,TH3_ROLL_OUT,
	TH3_SIDE_STEP, /*50*/
	TH3_MUKA_ZONE,TH3_MUKA_DIRECT,
	TH3_ESC_ZONECHASE,TH3_BEHIND,TH3_ZONE_POS, /*55*/
	TH3_DIRECT_POS,TH3_SHL_BREAK,
	TH3_ATTACK_EASY,TH3_ATTACK_STOMP, 
	TH3_CHASE_BEYOND,TH3_SAFEDIRECT_CHASE, /*61*/
	TH3_ATTACK_GRD,TH3_NSIGHT_ON,TH3_ATTACK_GRD_HIGH,
	TH3_THREAT,TH3_ATTACK_PEEK,TH3_STOPSIGN ,/*67*/
	TH3_APPROACH,TH3_DEPLOY,TH3_DEFENCE,TH3_DEFENCE2, /*71*/
	TH3_SYM_ATTACK,TH3_SYM_RELOAD,TH3_ATTACK_LOCKER,
	TH3_WAKE,TH3_INTRUDE_ZONE_POS, 	/*76*/
	TH3_DIRECT_CHASE_JUMP,TH3_START_JUMP,
	TH3_ZONE_CHASE_NEAR_ATTACK,TH3_DIRECT_CHASE_NEAR_ATTACK,
	TH3_KATANA_GURAD,TH3_JUMP_ATTACK ,TH3_ATTACK_HANG,TH3_ABS_ESCAPE,TH3_ATTACK_EASY_LIE,
	TH3_DISCOVERY_STINGER,TH3_DODGE_NIKITA,TH3_GRD_M4_RELOAD,TH3_GRD_M4_SHOOT,TH3_MEDICATION,
	TH3_FOUND_PL
} ;

	/*アクションパッド */
enum {
	SP_NONE,
	SP_DOWNBACK,
	SP_READYGUN,
	SP_SHOOTGUN,
	SP_ATTACK_KICK,		/*回し蹴り*/
	SP_CLE_GOSIGN,	/* ＧＯサイン */
	SP_RELOAD,		/* リロード */
	SP_RELOAD_SQUAT,/* しゃがみリロード */
	SP_TURN_GO_L,	/*90度回転踏み出し*/
	SP_TURN_GO_R,	/*90度回転踏み出し*/
	SP_MOVE_RUN, 
	SP_MOVE_RUN_R,/*右走り*/
	SP_MOVE_RUN_L, /*左走り*/
	SP_SQUATGUN, /*下段攻撃*/
	SP_SQUATSHOOTGUN,
	SP_GRD_LOW,			/* グレネード */
	SP_GRD_HIGH,
	SP_SQUATHIDE, /* しゃがみ待機 */
	SP_BIKKURI,	/* 銃を向けられた */
	SP_BIKKURI_HIDE,	/*伏せてかわす*/
	SP_ROLL_L,	/*しゃがみ転がり*/
	SP_ROLL_R,	/*しゃがみ転がり*/
	SP_STEP_L,	/*横っ飛び*/
	SP_STEP_R,
	SP_MUKADE_WALK_LOW, /* ムカデ歩き */
	SP_MUKADE_WALK_HI, /* ムカデ歩き */
	SP_MUKADE_WALK_VL, /* ムカデ歩き*/
	SP_READYGUN_SHL,	/*盾構え*/
	SP_SHOOTGUN_SHL,	/*盾発砲*/
	SP_APPROCH,			/*発砲にじり寄り*/
	SP_BEHIND,			/*張り付き*/
	SP_BACKWALK,			/*後退*/
	SP_STAND_DEFENCE, 	/*立ち防御*/
	SP_SQUAT_DEFENCE, 	/*座り防御*/
	SP_SHL_BREAK,		/*盾壊れ*/
	SP_SHL_PUSH,		/*盾で押す攻撃*/
	SP_SHL_SIDE_READYGUN,	/*盾の横から構え*/
	SP_SHL_SIDE_SHOOTGUN,	/*盾の横から撃つ*/
	SP_STOMP,			/*踏みつけ攻撃*/
	SP_STOMP_WAKE,		/*起こし攻撃*/
	SP_NSIGHT_ON,		/*暗視ゴーグル付ける*/
	SP_KICK_LOCKER ,	/*ロッカー蹴り*/
	SP_ATTACK_PUNCH_L ,
	SP_ATTACK_PUNCH_R ,
	SP_ATTACK_KICK_L ,
	SP_ATTACK_KICK_R ,
	/*銃撃戦用*/
	SP_STAND_STILL,
	SP_SHOT_POS,		/*プレイヤ以外の指定点を狙う*/

	SP_PEEK_HIGH_R,
	SP_PEEK_HIGH_IDLE_R,
	SP_PEEK_HIGH_END_R,
	SP_PEEK_HIGH_L,
	SP_PEEK_HIGH_IDLE_L,
	SP_PEEK_HIGH_END_L,

	SP_SPS_SETUP,	/*ショットガン構え*/
	SP_SPS_FIRE,	/*ショットガン発砲*/
	SP_STOPSIGN,	/*止まれっ！*/
	SP_OPEN_LOCKER,	/*ロッカー開け*/
	SP_INTRUDE_FIRE,	/*超低位置射撃*/
	SP_RELOAD_SPS,		/*スパスリロード*/
	/*以下天狗専用*/
	SP_TNG_JUMP,			/*ジャンプ*/
	SP_TNG_JUMP_LEVEL,		/*ジャンプ*/
	SP_BACK_TURN,			/*バク転*/
	SP_SLIDING,			/*スライディング*/
	SP_KATANA_GUARD,
	SP_JUMP_ATTACK,
	SP_HANG_START,
	SP_GRD_RELOAD,
	SP_GRD_M4_SHOOT,
	SP_AIM_POS,
	SP_SHOOTSPS2,		/*排莢してから発砲*/
	SP_WAIT,
	SP_READYGUN_PB,		/*負傷中の構え*/
	SP_MEDICATION,
	SP_DISCOVERY,
	SP_BEYOND			/**/
} ;
/*何か見つけてビックリ　何を見たか*/
enum {
	AT_FOUND_NONE,
	AT_FOUND_STINGER,
	AT_FOUND_NIKITA
} ;
