#
# Makefile for MGS2 Sub Module
#	各ソースがおかれたディレクトリ用 makefile
#
# 1999/07/08 K.Uehara
# 2000/01/20 T.Morita Revised
# $Id: makefile,v 1.3 2002/04/19 12:01:42 usr04098 Exp $
#

# ベースディレクトリ
BASEDIR = ../../..

# ライブラリ名

LIBNAME = morita.a

# オブジェクトリスト
SRCS = put_flag.c 
OBJS = $(SRCS:.c=.o)
XOBJECTS = $(SRCS:.c=.obj)

# 設定の実体

include $(BASEDIR)/makefile.sub

# 依存関係のリスト


