#
# Makefile for MGS2 Sub Module
#	各ソースがおかれたディレクトリ用 makefile
#
# 2002/03/12 S.Yamashita
# $Id: makefile,v 1.1.1.3 2002/11/19 11:51:53 Yoshizawa1 Exp $
#

# ベースディレクトリ
BASEDIR = ../../..

# ライブラリ名
LIBNAME = yamashita.a

# オブジェクトリスト
OBJECTS = sy_print.o sy_memcpy.o sy_util.o

XOBJECTS = sy_print.obj sy_memcpy.obj sy_util.obj

# ここでのローカルフラグリスト
LOCAL_INCLUDES = 
LOCAL_DEFINES = 
LOCAL_OPTIONS = 

# 設定の実体
include $(BASEDIR)/makefile.sub
