//------------------------------------------------------------------------------------------
// BP_TrophySystemX360.cpp
//
// X360 platform specific trophy functions.
//------------------------------------------------------------------------------------------

#include "Engine/Stdafx.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <xtl.h>

#include "BP_TrophySystem.h"
#include "BP_SaveLoadMGS.h"
#include "Engine/System/X360COsContext.h"

#include "../../../Builds/DiskBuilds/UseDiskBuild.h"

#if MGS_VERSION==2
#include "..\..\..\Builds\DiskBuilds\X360_XLAST_files\XLAST_files\mgshd.spa.h"
#elif MGS_VERSION==3
#include "..\..\..\Builds\DiskBuilds\X360_XLAST_files\XLAST_files\mgshd.spa.h"
#endif

#define BP_MAX_ACHIEVEMENTS		51
#define BP_NO_ACHIEVEMENT        -1

//----------------------------------------------------------------------------

// Mapping from PS3 trophy enum to X360 achievement defines.
// Automatically generated by excel macro.
// See: //depot/dev/MGS3/GameData/TROPDIR/NPWR02381_00/ExportTrophies_ExcelMacro.txt

static DWORD const skAchievementRemapping[ BP_MAX_ACHIEVEMENTS ] =
{
	0,	// kTRP_Platinum - OS unlocks on PS3, doesn't exist on X360
#if MGS_VERSION==2
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_001,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_002,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_003,
   ACHIEVEMENT_TROPHY_004,
   ACHIEVEMENT_TROPHY_005,
   ACHIEVEMENT_TROPHY_006,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_007,
   ACHIEVEMENT_TROPHY_008,
   ACHIEVEMENT_TROPHY_009,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_010,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_011,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_012,
   ACHIEVEMENT_TROPHY_013,
   ACHIEVEMENT_TROPHY_014,
   ACHIEVEMENT_TROPHY_015,
   ACHIEVEMENT_TROPHY_016,
   ACHIEVEMENT_TROPHY_017,
   ACHIEVEMENT_TROPHY_018,
   ACHIEVEMENT_TROPHY_019,
   ACHIEVEMENT_TROPHY_020,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_021,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_022,
   ACHIEVEMENT_TROPHY_023,
   ACHIEVEMENT_TROPHY_024,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
#endif 

#if MGS_VERSION==3
   ACHIEVEMENT_TROPHY_025,
   ACHIEVEMENT_TROPHY_026,
   ACHIEVEMENT_TROPHY_027,
   ACHIEVEMENT_TROPHY_028,
   ACHIEVEMENT_TROPHY_029,
   ACHIEVEMENT_TROPHY_030,
   ACHIEVEMENT_TROPHY_031,
   ACHIEVEMENT_TROPHY_032,
   ACHIEVEMENT_TROPHY_033,
   ACHIEVEMENT_TROPHY_034,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_035,
   ACHIEVEMENT_TROPHY_036,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_037,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_038,
   ACHIEVEMENT_TROPHY_039,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_040,
   ACHIEVEMENT_TROPHY_041,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_042,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_043,
   ACHIEVEMENT_TROPHY_044,
   ACHIEVEMENT_TROPHY_045,
   ACHIEVEMENT_TROPHY_046,
   BP_NO_ACHIEVEMENT,
   ACHIEVEMENT_TROPHY_047,
   ACHIEVEMENT_TROPHY_048,
   ACHIEVEMENT_TROPHY_049,
   ACHIEVEMENT_TROPHY_050,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
   BP_NO_ACHIEVEMENT,
#endif
};

// whether or not achievements are disabled for a given player.
static bool sbAchievementsEnabled = false;

//----------------------------------------------------------------------------

extern "C" void BP_TrophySystem_Init()
{
#if BP_TGS_DEMO()
   // No trophies on TGS Demo as per KJP 2011-08-24
	printf("BP_TrophySystem_Init() - Trophies disabled for TGS Demo.\n");
   return;
#endif

	// automatic sign-in.
#if 0
	XOnlineStartup();
	XShowSigninUI( 1, 0 );
#endif

   //TED - there's an interdependency b/t trophy and savedata initialization on PS3.
   //There's no such issue on X360, but for consistency I'm initializing savedata in
   //the same place here.
   MGS_SaveStatus_Init();

	// enable achievements.
	sbAchievementsEnabled = true;
}

//----------------------------------------------------------------------------

extern "C" void BP_TrophySystem_Shutdown()
{
	sbAchievementsEnabled = false;
}

//----------------------------------------------------------------------------

extern "C" int BP_TrophySystem_UpdateInProgress()
{
	return 0;
}

//----------------------------------------------------------------------------

extern "C" void BP_TrophySystem_Disable()
{
	// disable trophies.
	sbAchievementsEnabled = false;
}

//----------------------------------------------------------------------------

extern "C" void BP_TrophySystem_Enable()
{
   // disable trophies.
   sbAchievementsEnabled = true;
}

//----------------------------------------------------------------------------

extern "C" int BP_TrophySystem_IsDisabled()
{
   return sbAchievementsEnabled ? 0 : 1;
}

//----------------------------------------------------------------------------

extern "C" void BP_TrophySystem_UnlockTrophy(ETrophies trophyId)
{
	// this should not be used!  First off, kTRP_Platinum is only
	BPE_ASSERT( trophyId != kTRP_Platinum, "kTRP_Platinum may not be used as a trophy!\n" );
	BPE_ASSERT( trophyId < kTRP_Count, "Invalid trophy index!\n" );

	// simply return if achievements are disabled.
	if ( !sbAchievementsEnabled )
		return;

	// get the index of the achievement within the achievements array.
	DWORD const achievementId = skAchievementRemapping[trophyId];
   if (achievementId == BP_NO_ACHIEVEMENT)
   {
      // This achievement isn't enabled for this game (2 or 3)
      bpe_debugger_printf("X360 - NO ACHIEVEMENT(%d): %s\n", trophyId, BP_TrophySystem_GetDebugString(trophyId));
      return;
   }

   COsContext* pOsContext = (COsContext*)gpOsContext;

	// Unlock achievement
	XUSER_ACHIEVEMENT userAchievement;
	userAchievement.dwUserIndex = pOsContext->mSignedInUser;
	userAchievement.dwAchievementId = achievementId;

   pOsContext->AddAchievement(userAchievement);

   bpe_debugger_printf("X360 - ACHIEVEMENT UNLOCKED(%d/%d): %s\n", trophyId, achievementId, BP_TrophySystem_GetDebugString(trophyId));
}

//----------------------------------------------------------------------------
