#
# Makefile for MGS2 Sub Module
#	各ソースがおかれたディレクトリ用 makefile
#

# ベースディレクトリ
BASEDIR = ../../..

# ライブラリ名

LIBNAME = shibata.a

# オブジェクトリスト
OBJECTS = flour.o flour_spread.o flour_splay.o flour_pers.o  flour_Fall.o flour_sara.o flour_moku.o flour_gas3.o

XOBJECTS = flour.obj flour_spread.obj flour_splay.obj flour_pers.obj  flour_Fall.obj flour_sara.obj flour_moku.obj flour_gas3.obj
# ここでのローカルフラグリスト

LOCAL_INCLUDES =
LOCAL_DEFINES = 
LOCAL_OPTIONS =

# 設定の実体

include $(BASEDIR)/makefile.sub

# 依存関係のリスト


