@echo off

call ..\..\..\cp4_environment.bat

bin2c ICON_TANKER.PNG ICON_TANKER.PNG.h ICON_TANKER_PNG
bin2c ICON_PLANT.PNG ICON_PLANT.PNG.h ICON_PLANT_PNG
bin2c ICON_VR.PNG ICON_VR.PNG.h ICON_VR_PNG
bin2c ICON_SNAKETALES.PNG ICON_SNAKETALES.PNG.h ICON_SNAKETALES_PNG
bin2c ICON_PHOTO.PNG ICON_PHOTO.PNG.h ICON_PHOTO_PNG


bin2c ICON_TANKER_X360.PNG ICON_TANKER_X360.PNG.h ICON_TANKER_PNG
bin2c ICON_PLANT_X360.PNG ICON_PLANT_X360.PNG.h ICON_PLANT_PNG
bin2c ICON_VR_X360.PNG ICON_VR_X360.PNG.h ICON_VR_PNG
bin2c ICON_SNAKETALES_X360.PNG ICON_SNAKETALES_X360.PNG.h ICON_SNAKETALES_PNG
bin2c ICON_PHOTO_X360.PNG ICON_PHOTO_X360.PNG.h ICON_PHOTO_PNG
