/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /u/develop/mj001b/cvsroot/tools/layout2d/Attic/lex.yy.c,v 1.8 2002/05/24 11:07:07 usr10656 Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 122
#define YY_END_OF_BUFFER 123
static yyconst short int yy_accept[464] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  123,  121,  120,  108,  116,  113,  114,  111,
      109,  115,  110,  119,  112,  121,  121,  121,  121,  117,
      118,   53,   67,  112,  121,  121,  121,  121,  121,  121,
      121,  121,   71,   71,  122,   71,   70,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   21,  110,  112,

       25,   25,   25,   24,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   72,  112,  121,  121,   76,   76,
       76,   75,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,  103,  112,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  107,  107,  107,  106,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,   96,  112,
       92,  121,  121,  121,   48,  112,  121,  121,  121,   52,
       52,   52,   51,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   38,  112,  121,  121,  121,  121,  121,
      121,   42,   42,   42,   41,   42,   42,   42,   42,   42,

       42,   42,   42,   42,   42,  112,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   43,  121,  121,   47,
       47,   47,   46,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,  119,    1,    0,    0,    0,    0,    3,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       68,   69,   22,   23,    5,    0,    0,   73,   74,    7,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   85,    0,    0,  104,  105,    9,   94,   93,
       91,   90,    0,   11,    0,    0,    0,   49,   50,   13,

        0,    0,    0,    0,    0,    0,   39,   40,   15,    2,
        4,    6,    8,   10,   12,   14,   16,    0,    0,   44,
       45,    0,   18,    0,    0,   59,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   97,    0,    0,
       80,    0,    0,    0,   95,    0,    0,    0,    0,    0,
        0,   32,    0,    0,    0,    0,    0,    0,    0,    0,
       56,    0,    0,    0,   63,   62,    0,    0,    0,   61,
        0,   78,    0,    0,    0,    0,    0,   99,  101,    0,
      100,   82,    0,    0,    0,  102,    0,    0,    0,   37,

       33,    0,    0,   34,    0,    0,    0,    0,    0,   54,
        0,    0,    0,   55,    0,    0,    0,    0,   89,   84,
        0,   88,    0,   98,    0,    0,    0,    0,    0,   28,
       36,   29,    0,    0,   26,   20,   19,    0,   57,   66,
       60,    0,   65,    0,   83,    0,   87,   86,   81,   27,
        0,   31,   35,    0,    0,   77,   79,    0,    0,   64,
       30,   58,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    1,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,    1,    1,
        1,    1,    1,    1,   15,    1,   16,    1,    1,   17,
        1,    1,   18,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   19,    1,    1,
        1,   20,    1,    1,    1,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,    1,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   46,    1,   47,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[48] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[473] =
    {   0,
        0,   46,   91,    0,  135,  181,  226,    0,  263,  309,
       38,   65,  355,  401,  444,    0,  484,  530,   12,   17,
       86,  193,  576,  622,  665,    0,  706,  752,   11,   31,
      798,  844,  427,  426,  425,  424,  423,  422,  421,  420,
      419,  418,  417,  416,  415,  414,  412,  411,  889,  929,
      970, 1016,  418, 1064, 1064, 1064, 1064, 1064, 1064, 1064,
     1064, 1064,   28,   50,  409,  393,  393,  388,  361, 1064,
     1064, 1064, 1064,  391,  363,  364,   36,   45,  360,  358,
      369,  358, 1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064,
     1064, 1064, 1064, 1064,   67, 1064, 1064, 1064, 1064, 1064,

     1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064,
     1064,   68, 1064, 1064, 1064,  384,  357,  355, 1064, 1064,
     1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064,   71,
     1064, 1064, 1064,  381,   43,   44,  354,   58,  366,  349,
       57,  360,  343,   63, 1064, 1064, 1064, 1064, 1064, 1064,
     1064, 1064, 1064, 1064, 1064,   77, 1064, 1064, 1064,  375,
     1064,   82,   84,  364, 1064,  373,  357,  354,  341, 1064,
     1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064,
      113, 1064, 1064, 1064,  369,  351,  339,  344,  347,  334,
      349, 1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064,

     1064, 1064,  116, 1064, 1064,  361, 1064, 1064, 1064, 1064,
     1064,  354, 1064, 1064, 1064, 1064, 1064, 1064,  341, 1064,
      340,  339,  338,  337,  336,  335, 1064,  322,  317, 1064,
     1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064, 1064,
      119, 1064, 1064,  140, 1064,  306,  314,  317,  321, 1064,
      298,  304,  305,  299,  300,  102,  120,  307,  298,  299,
     1064, 1064, 1064, 1064, 1064,  309,  308, 1064, 1064, 1064,
      295,  303,  294,  295,  302,  301,  299,  296,  292,  273,
      262,  263,  267,  267,  278, 1064, 1064, 1064, 1064, 1064,
     1064, 1064,  283, 1064,  262,  256,  278, 1064, 1064, 1064,

      272,  260,  269,  256,  269,  264, 1064, 1064, 1064, 1064,
     1064, 1064, 1064, 1064, 1064, 1064, 1064,  248,  264, 1064,
     1064,  261, 1064,  250,  249, 1064,  248,  261,  248,  259,
      248,  237,  246,  250,  257,  238,  242,  224,  235,  231,
      226,  218,  221,  222,  229,  212,  218, 1064,  209,  225,
      214,  219,  207,  204, 1064,  219,  204,  219,  202,  210,
      207, 1064,  200,  194,  205,  192,  190,  186,  182,  177,
      182,  190,  184,  178, 1064, 1064,  177,  181,  188, 1064,
      173, 1064,  190,  185,  184,  171,  172, 1064, 1064,  176,
     1064, 1064,  178,  158,  177, 1064,  166,  162,  166, 1064,

     1064,  156,  169, 1064,  146,  158,  144,  148,  138, 1064,
      136,  138,  134, 1064,  147,  144,  127,  148, 1064, 1064,
      131, 1064,  143, 1064,  140,  140,  121,  139,  141, 1064,
     1064, 1064,  137,  128, 1064, 1064, 1064,  122, 1064, 1064,
     1064,  126, 1064,  117, 1064,  110, 1064, 1064, 1064, 1064,
      110, 1064, 1064,   90,   90, 1064, 1064,   83,   74, 1064,
     1064, 1064, 1064,  108,  102,   96,   44,   22,   18,   17,
        4,    0
    } ;

static yyconst short int yy_def[473] =
    {   0,
      464,  464,    2,    3,  465,  465,    2,    7,  466,  466,
        7,    7,  467,  467,    2,   15,  468,  468,    7,    7,
        7,    7,  469,  469,    2,   25,  470,  470,    7,    7,
      471,  471,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,    7,    7,
      472,  472,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,

      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,

      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,

      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,

      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,    0,  463,  463,  463,  463,  463,  463,  463,
      463,  463
    } ;

static yyconst short int yy_nxt[1112] =
    {   0,
      230,   55,   56,   57,  207,   58,   59,   60,   61,   62,
       63,   64,   65,   64,  159,   54,   54,  192,  170,  159,
       66,   54,  145,  206,  160,  161,  162,  163,  164,  160,
      161,  162,  163,  164,   67,   54,   68,   69,  244,  244,
       56,  244,  115,  206,  119,   70,   71,   55,   56,   57,
      116,   58,   59,   60,   61,   62,   63,   64,   65,   64,
      244,  244,  117,  244,  253,  255,   66,   56,  273,  115,
      118,  261,  263,  254,  271,  268,  272,  116,  274,  256,
       67,  286,   68,   69,  280,  281,  276,  284,   56,  117,
      165,   70,   71,   72,  277,   73,  101,  118,  166,  285,

      262,  264,   83,   74,  269,  289,  167,  291,   54,  462,
      287,   54,   75,  461,  460,   76,  168,  298,  459,  290,
      307,  292,   77,  320,  169,   54,   78,   54,   79,   80,
      331,   81,  458,  332,  457,   82,   84,   85,   86,   87,
       88,   89,   90,   91,   92,   93,  299,   94,  333,  308,
      244,  244,  321,  244,   95,  456,  334,  455,  454,  453,
      452,  451,  450,  449,  448,  447,  446,  445,  444,  443,
      442,  441,  440,  439,  438,  437,  436,  435,  434,  433,
       96,   97,   84,   85,   86,   87,   88,   89,   90,   91,
       92,   93,  432,   94,  431,   56,  430,  165,  429,  428,

       95,  427,  426,  425,  424,  166,  423,  422,  421,  420,
      419,  418,  417,  167,  416,  415,  414,  413,  412,  411,
      410,  409,  408,  168,  407,  406,   96,   97,   85,  405,
       98,  169,  404,  403,  402,  401,   99,   54,  100,   54,
      400,  399,  398,  397,  396,  395,   54,  394,  393,  392,
      391,  390,  389,  388,  387,  386,  385,  384,  383,  382,
       54,  381,   54,   54,  102,   85,  103,  104,  105,  106,
      107,  108,  109,  110,  380,  111,  379,  378,  377,  376,
      375,  374,  112,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,

      356,  355,  354,  353,  352,  351,  350,  349,  113,  114,
      102,   85,  103,  104,  105,  106,  107,  108,  109,  110,
      348,  111,  347,  346,  345,  344,  343,  342,  112,  341,
      340,  339,  338,  337,  336,  335,  330,  329,  328,  327,
      326,  325,  324,  323,  322,  319,  318,  317,  316,  315,
      314,  313,  312,  311,  113,  114,  120,   85,  121,  122,
      123,  124,  125,  126,  127,  128,  310,  129,  309,  306,
      305,  304,  303,  302,  130,  301,  300,  297,  296,  295,
      294,  293,  288,  283,  282,  279,  278,  275,  270,  267,
      266,  265,  260,  259,  258,  257,  252,  251,  250,  249,

      131,  132,  120,   85,  121,  122,  123,  124,  125,  126,
      127,  128,  248,  129,  247,  246,  245,  463,  226,  226,
      130,  225,  225,  224,  224,  223,  223,  222,  222,  221,
      221,  220,  220,  219,  219,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  131,  132,  133,  463,
      463,  463,  463,  463,  463,  463,  134,  463,  463,  463,
      463,  463,  463,  463,  135,  463,  136,  463,  137,  463,
      463,  138,  463,  463,  463,  463,  139,  463,   54,  140,
       54,  141,  142,  143,  144,  146,   85,  147,  148,  149,
      150,  151,  152,  153,  154,  463,  155,  463,  463,  463,

      463,  463,  463,  156,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  157,
      158,  146,   85,  147,  148,  149,  150,  151,  152,  153,
      154,  463,  155,  463,  463,  463,  463,  463,  463,  156,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  157,  158,  171,   85,  172,
      173,  174,  175,  176,  177,  178,  179,  463,  180,  463,
      463,  463,  463,  463,  463,  181,  463,  463,  463,  463,

      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  182,  183,  171,   85,  172,  173,  174,  175,  176,
      177,  178,  179,  463,  180,  463,  463,  463,  463,  463,
      463,  181,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  182,  183,  184,
      463,  463,  463,  463,  463,  463,  463,  185,  463,  463,
      463,  463,  463,  463,  463,   54,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  186,  187,  463,   54,

      463,  188,  189,  190,  463,  463,  191,  193,   85,  194,
      195,  196,  197,  198,  199,  200,  201,  463,  202,  463,
      463,  463,  463,  463,  463,  203,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  204,  205,  193,   85,  194,  195,  196,  197,  198,
      199,  200,  201,  463,  202,  463,  463,  463,  463,  463,
      463,  203,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  204,  205,  208,

       85,  209,  463,  210,  211,  212,  213,  214,  215,  463,
      216,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  217,  218,  208,   85,  209,  463,  210,
      211,  212,  213,  214,  215,  463,  216,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  217,
      218,   56,  463,  227,  463,  463,  463,  463,  463,   63,

       64,  463,   64,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  228,
      463,  463,  463,  463,  463,  463,  229,  463,  463,  463,
      191,   56,  463,  227,  463,  463,  463,  463,  463,   63,
       64,  463,   64,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  228,
      463,  463,  463,  463,  463,  463,  229,  463,  463,  463,
      191,  231,   85,  232,  233,  234,  235,  236,  237,  238,
      239,  463,  240,  463,  463,  463,  463,  463,  463,  241,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,

      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  242,  243,  231,   85,  232,
      233,  234,  235,  236,  237,  238,  239,  463,  240,  463,
      463,  463,  463,  463,  463,  241,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  242,  243,   53,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,

      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463
    } ;

static yyconst short int yy_chk[1112] =
    {   0,
      472,    1,    1,    1,  471,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   19,   29,   19,  470,  469,   20,
        1,   20,  468,   29,   19,   19,   19,   19,   19,   20,
       20,   20,   20,   20,    1,   30,    1,    1,   63,   63,
       11,   63,   11,   30,  467,    1,    1,    2,    2,    2,
       11,    2,    2,    2,    2,    2,    2,    2,    2,    2,
       64,   64,   11,   64,   77,   78,    2,   12,  136,   12,
       11,   95,  112,   77,  135,  130,  135,   12,  136,   78,
        2,  156,    2,    2,  141,  141,  138,  144,   21,   12,
       21,    2,    2,    3,  138,    3,  466,   12,   21,  144,

       95,  112,  465,    3,  130,  162,   21,  163,  464,  459,
      156,    3,    3,  458,  455,    3,   21,  181,  454,  162,
      203,  163,    3,  241,   21,    3,    3,    3,    3,    3,
      256,    3,  451,  256,  446,    3,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,  181,    5,  257,  203,
      244,  244,  241,  244,    5,  444,  257,  442,  438,  434,
      433,  429,  428,  427,  426,  425,  423,  421,  418,  417,
      416,  415,  413,  412,  411,  409,  408,  407,  406,  405,
        5,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,  403,    6,  402,   22,  399,   22,  398,  397,

        6,  395,  394,  393,  390,   22,  387,  386,  385,  384,
      383,  381,  379,   22,  378,  377,  374,  373,  372,  371,
      370,  369,  368,   22,  367,  366,    6,    6,    7,  365,
        7,   22,  364,  363,  361,  360,    7,    7,    7,    7,
      359,  358,  357,  356,  354,  353,    7,  352,  351,  350,
      349,  347,  346,  345,  344,  343,  342,  341,  340,  339,
        7,  338,    7,    7,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,  337,    9,  336,  335,  334,  333,
      332,  331,    9,  330,  329,  328,  327,  325,  324,  322,
      319,  318,  306,  305,  304,  303,  302,  301,  297,  296,

      295,  293,  285,  284,  283,  282,  281,  280,    9,    9,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
      279,   10,  278,  277,  276,  275,  274,  273,   10,  272,
      271,  267,  266,  260,  259,  258,  255,  254,  253,  252,
      251,  249,  248,  247,  246,  229,  228,  226,  225,  224,
      223,  222,  221,  219,   10,   10,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,  212,   13,  206,  191,
      190,  189,  188,  187,   13,  186,  185,  169,  168,  167,
      166,  164,  160,  143,  142,  140,  139,  137,  134,  118,
      117,  116,   82,   81,   80,   79,   76,   75,   74,   69,

       13,   13,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   68,   14,   67,   66,   65,   53,   48,   47,
       14,   46,   45,   44,   43,   42,   41,   40,   39,   38,
       37,   36,   35,   34,   33,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   14,   14,   15,    0,
        0,    0,    0,    0,    0,    0,   15,    0,    0,    0,
        0,    0,    0,    0,   15,    0,   15,    0,   15,    0,
        0,   15,    0,    0,    0,    0,   15,    0,   15,   15,
       15,   15,   15,   15,   15,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,    0,   17,    0,    0,    0,

        0,    0,    0,   17,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   17,
       17,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,    0,   18,    0,    0,    0,    0,    0,    0,   18,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   18,   18,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,    0,   23,    0,
        0,    0,    0,    0,    0,   23,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   23,   23,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,    0,   24,    0,    0,    0,    0,    0,
        0,   24,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   24,   24,   25,
        0,    0,    0,    0,    0,    0,    0,   25,    0,    0,
        0,    0,    0,    0,    0,   25,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   25,   25,    0,   25,

        0,   25,   25,   25,    0,    0,   25,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,    0,   27,    0,
        0,    0,    0,    0,    0,   27,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   27,   27,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,    0,   28,    0,    0,    0,    0,    0,
        0,   28,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   28,   28,   31,

       31,   31,    0,   31,   31,   31,   31,   31,   31,    0,
       31,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   31,   31,   32,   32,   32,    0,   32,
       32,   32,   32,   32,   32,    0,   32,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   32,
       32,   49,    0,   49,    0,    0,    0,    0,    0,   49,

       49,    0,   49,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   49,
        0,    0,    0,    0,    0,    0,   49,    0,    0,    0,
       49,   50,    0,   50,    0,    0,    0,    0,    0,   50,
       50,    0,   50,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   50,
        0,    0,    0,    0,    0,    0,   50,    0,    0,    0,
       50,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,    0,   51,    0,    0,    0,    0,    0,    0,   51,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   51,   51,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,    0,   52,    0,
        0,    0,    0,    0,    0,   52,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   52,   52,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,

      463,  463,  463,  463,  463,  463,  463,  463,  463,  463,
      463
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "2d_layout.l"
#define INITIAL 0
#line 2 "2d_layout.l"
#include "util.h"

int num_line = 0;
char lexstrbuf[ 256 ] = {0};
int strcnt = 0;
#define DEF 1
#define DEFSTR 2
#define TRI 3
#define TRISTR 4
#define ST 5
#define STSTR 6
#define MODE 7
#define MDSTR 8
#define ALPHA 9
#define AC 10
#define ACSTR 11
#define TR 12
#define TRSTR 13
#define MORF 14

#define COMM 15
#define COMM_DEF 16
#define COMM_TRI 17
#define COMM_ST 18
#define COMM_MD 19
#define COMM_ALP 20
#define COMM_AC 21
#define COMM_TR 22
#define COMM_MF 23

#define KTR 24
#define KTRSTR 25

#line 797 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 11 "2d_layout.l"

#line 950 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 464 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1064 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 12 "2d_layout.l"
{ BEGIN COMM; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 13 "2d_layout.l"
{ BEGIN INITIAL; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 15 "2d_layout.l"
{ BEGIN COMM_DEF; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 16 "2d_layout.l"
{ BEGIN DEF; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 18 "2d_layout.l"
{ BEGIN COMM_ST; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 19 "2d_layout.l"
{ BEGIN ST; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 21 "2d_layout.l"
{ BEGIN COMM_MD; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 22 "2d_layout.l"
{ BEGIN MODE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 24 "2d_layout.l"
{ BEGIN COMM_ALP; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 25 "2d_layout.l"
{ BEGIN ALPHA; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 27 "2d_layout.l"
{ BEGIN COMM_AC; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 28 "2d_layout.l"
{ BEGIN AC; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 30 "2d_layout.l"
{ BEGIN COMM_TR; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 31 "2d_layout.l"
{ BEGIN TR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 33 "2d_layout.l"
{ BEGIN COMM_MF; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 34 "2d_layout.l"
{ BEGIN MORF; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 36 "2d_layout.l"
;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 39 "2d_layout.l"
{
			  BEGIN DEF;
			  return OBJ;
			}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 43 "2d_layout.l"
{
			  BEGIN ST;
			  return STAT;
			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "2d_layout.l"
{
			  BEGIN TRI;
			  return REFTRI;
			}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "2d_layout.l"
{
			  BEGIN TRISTR;
			  strcnt = 0;
			}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 56 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\"'; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 57 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\n'; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 58 "2d_layout.l"
{
			  lexstrbuf[strcnt] = 0;
			  yylval.str = &poolbuf[pool(lexstrbuf)];
			  BEGIN INITIAL;
			  return STRING;
			}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "2d_layout.l"
{ lexstrbuf[strcnt++] = yytext[0]; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 66 "2d_layout.l"
{
			  BEGIN AC;
			  return ACT;
			}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 70 "2d_layout.l"
{
			  BEGIN INITIAL;
			  return ACT_END;
			}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 74 "2d_layout.l"
{
			  BEGIN TR;
			  return TRK;
			}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 78 "2d_layout.l"
{
			  BEGIN AC;
			  return TRK_END;
			}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 82 "2d_layout.l"
{
			  BEGIN KTR;
			  return KEY;
			}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 86 "2d_layout.l"
{
			  BEGIN AC;
			  return KEY_END;
			}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 90 "2d_layout.l"
return TRK_SET;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 91 "2d_layout.l"
return TRK_MORF;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 92 "2d_layout.l"
return TRK_WAIT;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 93 "2d_layout.l"
return TRK_SIGN;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 94 "2d_layout.l"
{
			  yylval.i_num = 0;
			  return TRK_SPINDIR;
			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 98 "2d_layout.l"
{
			  yylval.i_num = 1;
			  return TRK_SPINDIR;
			}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 102 "2d_layout.l"
{
			  BEGIN TRSTR;
			  strcnt = 0; /* 文字列を最初から */
			}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 106 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\"'; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 107 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\n'; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 108 "2d_layout.l"
{
			  lexstrbuf[strcnt] = 0;
			  yylval.str = &poolbuf[pool(lexstrbuf)];
			  BEGIN TR;
			  return STRING;
			}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 114 "2d_layout.l"
{ lexstrbuf[strcnt++] = yytext[0]; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 117 "2d_layout.l"
{
			  BEGIN KTRSTR;
			  strcnt = 0; /* 文字列を最初から */
			}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 121 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\"'; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 122 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\n'; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 123 "2d_layout.l"
{
			  lexstrbuf[strcnt] = 0;
			  yylval.str = &poolbuf[pool(lexstrbuf)];
			  BEGIN KTR;
			  return STRING;
			}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 129 "2d_layout.l"
{ lexstrbuf[strcnt++] = yytext[0]; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 132 "2d_layout.l"
{
			  BEGIN ACSTR;
			  strcnt = 0; /* 文字列を最初から */
			}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 136 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\"'; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 137 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\n'; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 138 "2d_layout.l"
{
			  lexstrbuf[strcnt] = 0;
			  yylval.str = &poolbuf[pool(lexstrbuf)];
			  BEGIN AC;
			  return STRING;
			}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 144 "2d_layout.l"
{ lexstrbuf[strcnt++] = yytext[0]; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 146 "2d_layout.l"
{
			  num_line++;
			  BEGIN INITIAL;
			  return NL;
			}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 151 "2d_layout.l"
{
			  yylval.spr_id = SP_EMPTY;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 155 "2d_layout.l"
{
			  yylval.spr_id = SP_POINT;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 159 "2d_layout.l"
{
			  yylval.spr_id = SP_LINE;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 163 "2d_layout.l"
{
			  yylval.spr_id = SP_LINESTRIP;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 167 "2d_layout.l"
{
			  yylval.spr_id = SP_LINESTRIP;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 171 "2d_layout.l"
{
			  yylval.spr_id = SP_BOX;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 175 "2d_layout.l"
{
			  yylval.spr_id = SP_SPRITE;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 179 "2d_layout.l"
{
			  yylval.spr_id = SP_ZOOM;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 183 "2d_layout.l"
{
			  yylval.spr_id = SP_SPIN;
			  DBG("SPIN!!\n");
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 188 "2d_layout.l"
{
			  yylval.spr_id = SP_POLY;
			  DBG("POLY!!\n");
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 193 "2d_layout.l"
{
			  yylval.spr_id = SP_TRIANGLE;
			  return OBJ_ATTRIB;
			}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 197 "2d_layout.l"
return OBJ_VERTEX;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 198 "2d_layout.l"
return OBJ_PARENT;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 199 "2d_layout.l"
{
			  BEGIN DEFSTR;
			  strcnt = 0; /* 文字列を最初から */
			}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 203 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\"'; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 204 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\n'; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 205 "2d_layout.l"
{
			  lexstrbuf[strcnt] = 0;
			  yylval.str = &poolbuf[pool(lexstrbuf)];
			  BEGIN DEF;
			  return STRING;
			}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 211 "2d_layout.l"
{
			  DBG("str: %c\n", yytext[0]);
			  lexstrbuf[strcnt++] = yytext[0];
			}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 215 "2d_layout.l"
{
			  BEGIN STSTR;
			  strcnt = 0;
			}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 219 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\"'; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 220 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\n'; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 221 "2d_layout.l"
{
			  lexstrbuf[strcnt] = 0;
			  yylval.str = &poolbuf[pool(lexstrbuf)];
			  BEGIN ST;
			  return STRING;
			}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 227 "2d_layout.l"
{ lexstrbuf[strcnt++] = yytext[0]; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 229 "2d_layout.l"
{
			  BEGIN INITIAL;
			  return STAT_END;
			}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 234 "2d_layout.l"
{
			  BEGIN MODE;
			  return STAT_MODE;
			}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 239 "2d_layout.l"
{
			  BEGIN ST;
			  return STAT_MODE_END;
			}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 244 "2d_layout.l"
return MODE_TEX;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 245 "2d_layout.l"
return MODE_VERTEX;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 246 "2d_layout.l"
return MODE_SIZE;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 247 "2d_layout.l"
return MODE_CENTER;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 248 "2d_layout.l"
return MODE_ANGLE;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 249 "2d_layout.l"
return MODE_UV;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 250 "2d_layout.l"
return MODE_UVSIZE;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 251 "2d_layout.l"
return MODE_TEXOFF;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 252 "2d_layout.l"
return MODE_COLOR;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 253 "2d_layout.l"
{
			  BEGIN ALPHA;
			  return MODE_ALPHA;
			}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 257 "2d_layout.l"
{
			  yylval.i_num = 0;
			  return A_COL;
			}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 261 "2d_layout.l"
{
			  yylval.i_num = 1;
			  return A_COL;
			}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 265 "2d_layout.l"
{
			  yylval.i_num = 2;
			  return A_COL;
			}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 269 "2d_layout.l"
{
			  yylval.i_num = 0;
			  return A_ALP;
			}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 273 "2d_layout.l"
{
			  yylval.i_num = 1;
			  return A_ALP;
			}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 277 "2d_layout.l"
{
			  yylval.i_num = 2;
			  return A_ALP;
			}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 281 "2d_layout.l"
{
			  num_line++;
			  BEGIN MODE;
			  return NL;
			}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 287 "2d_layout.l"
return MODE_PRI;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 288 "2d_layout.l"
return MODE_MAGNI;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 289 "2d_layout.l"
return MODE_HIDE;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 290 "2d_layout.l"
return MODE_SHOW;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 291 "2d_layout.l"
return MODE_H_REV;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 292 "2d_layout.l"
return MODE_V_REV;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 293 "2d_layout.l"
{
			  BEGIN MDSTR;
			  strcnt = 0;
			  DBG("mode string\n");
			}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 298 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\"'; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 299 "2d_layout.l"
{ lexstrbuf[strcnt++] = '\n'; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 300 "2d_layout.l"
{
			  lexstrbuf[strcnt] = 0;
			  yylval.str = &poolbuf[pool(lexstrbuf)];
			  BEGIN MODE;
			  DBG("mode string end\n");
			  return STRING;
			}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 307 "2d_layout.l"
{ lexstrbuf[strcnt++] = yytext[0]; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 309 "2d_layout.l"
{
				  num_line++;
				  return NL;
				}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 313 "2d_layout.l"
return OP_ADD;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 314 "2d_layout.l"
{ DBG("----\n"); return OP_SUB; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 315 "2d_layout.l"
return OP_MUL;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 316 "2d_layout.l"
return OP_DIV;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 317 "2d_layout.l"
return OP_LP;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 318 "2d_layout.l"
return OP_RP;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 319 "2d_layout.l"
return OP_CUM;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 320 "2d_layout.l"
return OP_EXC;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 321 "2d_layout.l"
return OP_LBC;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 322 "2d_layout.l"
return OP_RBC;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 323 "2d_layout.l"
{
			  DBG("FLOAT\n");
			  yylval.f_num = atof(yytext);
			  return FLOAT;
			}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 328 "2d_layout.l"
;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 329 "2d_layout.l"
;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 331 "2d_layout.l"
ECHO;
	YY_BREAK
#line 1817 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DEF):
case YY_STATE_EOF(DEFSTR):
case YY_STATE_EOF(TRI):
case YY_STATE_EOF(TRISTR):
case YY_STATE_EOF(ST):
case YY_STATE_EOF(STSTR):
case YY_STATE_EOF(MODE):
case YY_STATE_EOF(MDSTR):
case YY_STATE_EOF(ALPHA):
case YY_STATE_EOF(AC):
case YY_STATE_EOF(ACSTR):
case YY_STATE_EOF(TR):
case YY_STATE_EOF(TRSTR):
case YY_STATE_EOF(MORF):
case YY_STATE_EOF(COMM):
case YY_STATE_EOF(COMM_DEF):
case YY_STATE_EOF(COMM_TRI):
case YY_STATE_EOF(COMM_ST):
case YY_STATE_EOF(COMM_MD):
case YY_STATE_EOF(COMM_ALP):
case YY_STATE_EOF(COMM_AC):
case YY_STATE_EOF(COMM_TR):
case YY_STATE_EOF(COMM_MF):
case YY_STATE_EOF(KTR):
case YY_STATE_EOF(KTRSTR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 464 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 464 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 463);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 331 "2d_layout.l"

