#
# Makefile for MGS2 Sub Module
#	各ソースがおかれたディレクトリ用 makefile
#
# 1999/07/08 K.Uehara
# $Id: makefile,v 1.17 2002/05/31 06:51:22 usr02774 Exp $
#

# ベースディレクトリ
BASEDIR = ../../..

# ライブラリ名

LIBNAME = mode.a

# オブジェクトリスト
OBJECTS = wp_chng2.o it_chng2.o menu_sub.o wp_chng1.o it_chng1.o common.o menu_pkt.o \
			text_scn.o shipworm.o pic_scn.o prm_util.o menu_cmd.o automenu.o

XOBJECTS = wp_chng2.obj it_chng2.obj xmenusub.obj wp_chng1.obj it_chng1.obj common.obj xmenupkt.obj \
			xtextscn.obj shipworm.obj xpic_scn.obj xprm_util.obj menu_cmd.obj automenu.obj

# ここでのローカルフラグリスト

LOCAL_INCLUDES = 
LOCAL_DEFINES = 
LOCAL_OPTIONS = 

# 設定の実体

include $(BASEDIR)/makefile.sub

# 依存関係のリスト

