#########################################################
# SCE CONFIDENTIAL
# PlayStation(R)Edge 1.2.0
# Copyright (C) 2007 Sony Computer Entertainment Inc.
# All Rights Reserved.
#########################################################


CELL_SDK ?= /usr/local/cell
CELL_MK_DIR ?= $(CELL_SDK)/samples/mk
include $(CELL_MK_DIR)/sdk.makedef.mk

SUBDIRS	= 	anim-sample \
		benchmark-sample \
		blendshape-anim-sample \
		character-sample \
		collision-sample \
		conditional-sample \
		dxt-sample \
		elephant-sample \
		fragment-patch-sample \
		geom-sample \
		locomotion-sample \
		mirror-sample \
		occluders-sample \
		post-sample \
		post-sample-bloom \
		post-sample-hdr \
		post-sample-mblur \
		post-sample-mlaa \
		yvv-gaussian-sample \
		runtime-partitioning-sample \
		tunable-sample \
		vertexes-only-sample \
		writeback-sample \
		lzma-basic-inflate-sample \
		lzma-large-segmented-inflate-sample \
		lzma-inflate-retry-sample \
		lzo1x-basic-deflate-sample \
		lzo1x-basic-inflate-sample \
		lzo1x-inflate-retry-sample \
		lzo1x-large-segmented-inflate-sample \
		zlib-basic-inflate-sample \
		zlib-basic-deflate-inflate-sample \
		zlib-inflate-inplace-sample \
		zlib-inflate-retry-sample \
		zlib-large-segmented-inflate-sample \
		zlib-large-unsegmented-inflate-sample \
		zlib-localmemory-streaming-inflate-sample \
		zlib-streaming-inflate-sample

include $(CELL_MK_DIR)/sdk.target.mk

# Local Variables:
# mode: Makefile
# End:
