/* SCE CONFIDENTIAL
 * PlayStation(R)Edge 1.2.0
 * Copyright (C) 2009 Sony Computer Entertainment Inc.
 * All Rights Reserved.
 */

#include "utils.cg"
#include "logluv.cg"

struct VpOut
{
	float4      position        : POSITION; // Not used in fragment program
	half2       texcoord        : TEX0;
	half3       tanSpaceLightVec: TEX1; // For L dot N
	half3       tanSpaceViewVec : TEX2; // For H dot N
	half3       objSpaceLightVec: TEX3; // Used for computing attenuation only
	float4      current_pos		: TEX4;
	float4      prev_pos		: TEX5;
	float3      view_pos		: TEX6;
};

struct FpOut
{
	half4 color				: COLOR0;
	half4 motion_and_depth  : COLOR1;
};

// We would like to put binding semantics on the uniform inputs, but the current compiler does not allow this.
// cgfx2bin does print out the resource bindings of the uniform inputs on compilation and these can be used
// by the application to set values.
FpOut main(
		VpOut fragment, 
		uniform texobj2D colorMap : TEXUNIT0, 
		uniform texobj2D bumpGlossMap : TEXUNIT1, 
		uniform float4 depthAndMotionScale,
		float facing : FACE)
{
	FpOut result;
	
	float3 lightRgb = float3(0.5,0.5,0.5);
	float4 lightAtten = float4(1,0,0,0);
	float3 ambientRgb = float3(0.2,0.2,0.2);
	float specPow = 10;

	float d = length(fragment.objSpaceLightVec);
	float attenuation = saturate(1.0f/(lightAtten.x + lightAtten.y * d + lightAtten.z * d * d) - lightAtten.w);

	float4 normalGloss = tex2D(bumpGlossMap, fragment.texcoord.xy);
	normalGloss.xyz = normalGloss.xyz * 2.0f - 1.0f;
	normalGloss.z *= facing;
	float3 lightVec = normalize(fragment.tanSpaceLightVec);
	float3 viewVec = normalize(fragment.tanSpaceViewVec);
	float3 halfVec = normalize(lightVec + viewVec);
	float3 diffLighting = ambientRgb + attenuation * saturate(dot(lightVec, normalGloss.xyz)) * lightRgb;
	float3 specLighting = attenuation * pow(saturate(dot(halfVec, normalGloss.xyz)), specPow) * lightRgb;

	// color
	result.color = tex2D(colorMap, fragment.texcoord.xy);
	result.color = EncodeColor( result.color.rgb * diffLighting /* * float3( 1, 0, 0)*/ + normalGloss.w * specLighting);
	
	// linear depth
	float ld = saturate( ( length( fragment.view_pos) - depthAndMotionScale.y) * depthAndMotionScale.z);
	result.motion_and_depth.gb = PackDepth( ld );
	
	// motion vector
	result.motion_and_depth.ar = GenerateMotion( fragment.current_pos, fragment.prev_pos, depthAndMotionScale.x );

		
	return result;
}
