#
# Makefile for UVMap 
#	
#	Tue Nov 16 07:45:11 JST 1999
#	T.Morita
#
#	$Id: Makefile,v 1.1 2000/08/25 12:17:47 usr04098 Exp $
#
TARGET = makemar

INSTDIR = /u/develop/mj001b/tools/bin/linux

install:
	cp $(TARGET) $(INSTDIR)

