enum{
VRM_START = 0,
VRM_SNK_START = d:VRM_START,
VRM_SNK_SNK_START = d:VRM_SNK_START,
VRM_SNK_SNK_01_RAI = d:VRM_SNK_SNK_START,
VRM_SNK_SNK_01_NIN,
VRM_SNK_SNK_01_SNA,
VRM_SNK_SNK_01_PLI,
VRM_SNK_SNK_01_TUX,
VRM_SNK_SNK_01_PRE,
VRM_SNK_SNK_02_RAI,
VRM_SNK_SNK_02_NIN,
VRM_SNK_SNK_02_SNA,
VRM_SNK_SNK_02_PLI,
VRM_SNK_SNK_02_TUX,
VRM_SNK_SNK_02_PRE,
VRM_SNK_SNK_03_RAI,
VRM_SNK_SNK_03_NIN,
VRM_SNK_SNK_03_SNA,
VRM_SNK_SNK_03_PLI,
VRM_SNK_SNK_03_TUX,
VRM_SNK_SNK_03_PRE,
VRM_SNK_SNK_04_RAI,
VRM_SNK_SNK_04_NIN,
VRM_SNK_SNK_04_SNA,
VRM_SNK_SNK_04_PLI,
VRM_SNK_SNK_04_TUX,
VRM_SNK_SNK_04_PRE,
VRM_SNK_SNK_05_RAI,
VRM_SNK_SNK_05_NIN,
VRM_SNK_SNK_05_SNA,
VRM_SNK_SNK_05_PLI,
VRM_SNK_SNK_05_TUX,
VRM_SNK_SNK_05_PRE,
VRM_SNK_SNK_06_RAI,
VRM_SNK_SNK_06_NIN,
VRM_SNK_SNK_06_SNA,
VRM_SNK_SNK_06_PLI,
VRM_SNK_SNK_06_TUX,
VRM_SNK_SNK_06_PRE,
VRM_SNK_SNK_07_RAI,
VRM_SNK_SNK_07_NIN,
VRM_SNK_SNK_07_SNA,
VRM_SNK_SNK_07_PLI,
VRM_SNK_SNK_07_TUX,
VRM_SNK_SNK_07_PRE,
VRM_SNK_SNK_08_RAI,
VRM_SNK_SNK_08_NIN,
VRM_SNK_SNK_08_SNA,
VRM_SNK_SNK_08_PLI,
VRM_SNK_SNK_08_TUX,
VRM_SNK_SNK_08_PRE,
VRM_SNK_SNK_09_RAI,
VRM_SNK_SNK_09_NIN,
VRM_SNK_SNK_09_SNA,
VRM_SNK_SNK_09_PLI,
VRM_SNK_SNK_09_TUX,
VRM_SNK_SNK_09_PRE,
VRM_SNK_SNK_10_RAI,
VRM_SNK_SNK_10_NIN,
VRM_SNK_SNK_10_SNA,
VRM_SNK_SNK_10_PLI,
VRM_SNK_SNK_10_TUX,
VRM_SNK_SNK_10_PRE,
VRM_SNK_SNK_END = d:VRM_SNK_SNK_10_PRE,
VRM_SNK_ELM_START,
VRM_SNK_ELM_01_RAI = d:VRM_SNK_ELM_START,
VRM_SNK_ELM_01_NIN,
VRM_SNK_ELM_01_SNA,
VRM_SNK_ELM_01_PLI,
VRM_SNK_ELM_01_TUX,
VRM_SNK_ELM_01_PRE,
VRM_SNK_ELM_02_RAI,
VRM_SNK_ELM_02_NIN,
VRM_SNK_ELM_02_SNA,
VRM_SNK_ELM_02_PLI,
VRM_SNK_ELM_02_TUX,
VRM_SNK_ELM_02_PRE,
VRM_SNK_ELM_03_RAI,
VRM_SNK_ELM_03_NIN,
VRM_SNK_ELM_03_SNA,
VRM_SNK_ELM_03_PLI,
VRM_SNK_ELM_03_TUX,
VRM_SNK_ELM_03_PRE,
VRM_SNK_ELM_04_RAI,
VRM_SNK_ELM_04_NIN,
VRM_SNK_ELM_04_SNA,
VRM_SNK_ELM_04_PLI,
VRM_SNK_ELM_04_TUX,
VRM_SNK_ELM_04_PRE,
VRM_SNK_ELM_05_RAI,
VRM_SNK_ELM_05_NIN,
VRM_SNK_ELM_05_SNA,
VRM_SNK_ELM_05_PLI,
VRM_SNK_ELM_05_TUX,
VRM_SNK_ELM_05_PRE,
VRM_SNK_ELM_06_RAI,
VRM_SNK_ELM_06_NIN,
VRM_SNK_ELM_06_SNA,
VRM_SNK_ELM_06_PLI,
VRM_SNK_ELM_06_TUX,
VRM_SNK_ELM_06_PRE,
VRM_SNK_ELM_07_RAI,
VRM_SNK_ELM_07_NIN,
VRM_SNK_ELM_07_SNA,
VRM_SNK_ELM_07_PLI,
VRM_SNK_ELM_07_TUX,
VRM_SNK_ELM_07_PRE,
VRM_SNK_ELM_08_RAI,
VRM_SNK_ELM_08_NIN,
VRM_SNK_ELM_08_SNA,
VRM_SNK_ELM_08_PLI,
VRM_SNK_ELM_08_TUX,
VRM_SNK_ELM_08_PRE,
VRM_SNK_ELM_09_RAI,
VRM_SNK_ELM_09_NIN,
VRM_SNK_ELM_09_SNA,
VRM_SNK_ELM_09_PLI,
VRM_SNK_ELM_09_TUX,
VRM_SNK_ELM_09_PRE,
VRM_SNK_ELM_10_RAI,
VRM_SNK_ELM_10_NIN,
VRM_SNK_ELM_10_SNA,
VRM_SNK_ELM_10_PLI,
VRM_SNK_ELM_10_TUX,
VRM_SNK_ELM_10_PRE,
VRM_SNK_ELM_END = d:VRM_SNK_ELM_10_PRE,
VRM_SNK_END = d:VRM_SNK_ELM_END,
VRM_WPN_START,
VRM_WPN_HGN_START = d:VRM_WPN_START,
VRM_WPN_HGN_01_RAI = d:VRM_WPN_HGN_START,
VRM_WPN_HGN_01_SNA,
VRM_WPN_HGN_01_PLI,
VRM_WPN_HGN_01_TUX,
VRM_WPN_HGN_01_PRE,
VRM_WPN_HGN_02_RAI,
VRM_WPN_HGN_02_SNA,
VRM_WPN_HGN_02_PLI,
VRM_WPN_HGN_02_TUX,
VRM_WPN_HGN_02_PRE,
VRM_WPN_HGN_03_RAI,
VRM_WPN_HGN_03_SNA,
VRM_WPN_HGN_03_PLI,
VRM_WPN_HGN_03_TUX,
VRM_WPN_HGN_03_PRE,
VRM_WPN_HGN_04_RAI,
VRM_WPN_HGN_04_SNA,
VRM_WPN_HGN_04_PLI,
VRM_WPN_HGN_04_TUX,
VRM_WPN_HGN_04_PRE,
VRM_WPN_HGN_05_RAI,
VRM_WPN_HGN_05_SNA,
VRM_WPN_HGN_05_PLI,
VRM_WPN_HGN_05_TUX,
VRM_WPN_HGN_05_PRE,
VRM_WPN_HGN_END = d:VRM_WPN_HGN_05_PRE,
VRM_WPN_ASR_START,
VRM_WPN_ASR_01_RAI = d:VRM_WPN_ASR_START,
VRM_WPN_ASR_01_SNA,
VRM_WPN_ASR_01_PLI,
VRM_WPN_ASR_01_TUX,
VRM_WPN_ASR_01_PRE,
VRM_WPN_ASR_02_RAI,
VRM_WPN_ASR_02_SNA,
VRM_WPN_ASR_02_PLI,
VRM_WPN_ASR_02_TUX,
VRM_WPN_ASR_02_PRE,
VRM_WPN_ASR_03_RAI,
VRM_WPN_ASR_03_SNA,
VRM_WPN_ASR_03_PLI,
VRM_WPN_ASR_03_TUX,
VRM_WPN_ASR_03_PRE,
VRM_WPN_ASR_04_RAI,
VRM_WPN_ASR_04_SNA,
VRM_WPN_ASR_04_PLI,
VRM_WPN_ASR_04_TUX,
VRM_WPN_ASR_04_PRE,
VRM_WPN_ASR_05_RAI,
VRM_WPN_ASR_05_SNA,
VRM_WPN_ASR_05_PLI,
VRM_WPN_ASR_05_TUX,
VRM_WPN_ASR_05_PRE,
VRM_WPN_ASR_END = d:VRM_WPN_ASR_05_PRE,
VRM_WPN_C4C_START,
VRM_WPN_C4C_01_RAI = d:VRM_WPN_C4C_START,
VRM_WPN_C4C_01_SNA,
VRM_WPN_C4C_01_PLI,
VRM_WPN_C4C_01_TUX,
VRM_WPN_C4C_01_PRE,
VRM_WPN_C4C_02_RAI,
VRM_WPN_C4C_02_SNA,
VRM_WPN_C4C_02_PLI,
VRM_WPN_C4C_02_TUX,
VRM_WPN_C4C_02_PRE,
VRM_WPN_C4C_03_RAI,
VRM_WPN_C4C_03_SNA,
VRM_WPN_C4C_03_PLI,
VRM_WPN_C4C_03_TUX,
VRM_WPN_C4C_03_PRE,
VRM_WPN_C4C_04_RAI,
VRM_WPN_C4C_04_SNA,
VRM_WPN_C4C_04_PLI,
VRM_WPN_C4C_04_TUX,
VRM_WPN_C4C_04_PRE,
VRM_WPN_C4C_05_RAI,
VRM_WPN_C4C_05_SNA,
VRM_WPN_C4C_05_PLI,
VRM_WPN_C4C_05_TUX,
VRM_WPN_C4C_05_PRE,
VRM_WPN_C4C_END = d:VRM_WPN_C4C_05_PRE,
VRM_WPN_GRN_START,
VRM_WPN_GRN_01_RAI = d:VRM_WPN_GRN_START,
VRM_WPN_GRN_01_SNA,
VRM_WPN_GRN_01_PLI,
VRM_WPN_GRN_01_TUX,
VRM_WPN_GRN_01_PRE,
VRM_WPN_GRN_02_RAI,
VRM_WPN_GRN_02_SNA,
VRM_WPN_GRN_02_PLI,
VRM_WPN_GRN_02_TUX,
VRM_WPN_GRN_02_PRE,
VRM_WPN_GRN_03_RAI,
VRM_WPN_GRN_03_SNA,
VRM_WPN_GRN_03_PLI,
VRM_WPN_GRN_03_TUX,
VRM_WPN_GRN_03_PRE,
VRM_WPN_GRN_04_RAI,
VRM_WPN_GRN_04_SNA,
VRM_WPN_GRN_04_PLI,
VRM_WPN_GRN_04_TUX,
VRM_WPN_GRN_04_PRE,
VRM_WPN_GRN_05_RAI,
VRM_WPN_GRN_05_SNA,
VRM_WPN_GRN_05_PLI,
VRM_WPN_GRN_05_TUX,
VRM_WPN_GRN_05_PRE,
VRM_WPN_GRN_END = d:VRM_WPN_GRN_05_PRE,
VRM_WPN_PSG_START,
VRM_WPN_PSG_01_RAI = d:VRM_WPN_PSG_START,
VRM_WPN_PSG_01_SNA,
VRM_WPN_PSG_01_PLI,
VRM_WPN_PSG_01_TUX,
VRM_WPN_PSG_01_PRE,
VRM_WPN_PSG_02_RAI,
VRM_WPN_PSG_02_SNA,
VRM_WPN_PSG_02_PLI,
VRM_WPN_PSG_02_TUX,
VRM_WPN_PSG_02_PRE,
VRM_WPN_PSG_03_RAI,
VRM_WPN_PSG_03_SNA,
VRM_WPN_PSG_03_PLI,
VRM_WPN_PSG_03_TUX,
VRM_WPN_PSG_03_PRE,
VRM_WPN_PSG_04_RAI,
VRM_WPN_PSG_04_SNA,
VRM_WPN_PSG_04_PLI,
VRM_WPN_PSG_04_TUX,
VRM_WPN_PSG_04_PRE,
VRM_WPN_PSG_05_RAI,
VRM_WPN_PSG_05_SNA,
VRM_WPN_PSG_05_PLI,
VRM_WPN_PSG_05_TUX,
VRM_WPN_PSG_05_PRE,
VRM_WPN_PSG_END = d:VRM_WPN_PSG_05_PRE,
VRM_WPN_STG_START,
VRM_WPN_STG_01_RAI = d:VRM_WPN_STG_START,
VRM_WPN_STG_01_SNA,
VRM_WPN_STG_01_PLI,
VRM_WPN_STG_01_TUX,
VRM_WPN_STG_01_PRE,
VRM_WPN_STG_02_RAI,
VRM_WPN_STG_02_SNA,
VRM_WPN_STG_02_PLI,
VRM_WPN_STG_02_TUX,
VRM_WPN_STG_02_PRE,
VRM_WPN_STG_03_RAI,
VRM_WPN_STG_03_SNA,
VRM_WPN_STG_03_PLI,
VRM_WPN_STG_03_TUX,
VRM_WPN_STG_03_PRE,
VRM_WPN_STG_04_RAI,
VRM_WPN_STG_04_SNA,
VRM_WPN_STG_04_PLI,
VRM_WPN_STG_04_TUX,
VRM_WPN_STG_04_PRE,
VRM_WPN_STG_05_RAI,
VRM_WPN_STG_05_SNA,
VRM_WPN_STG_05_PLI,
VRM_WPN_STG_05_TUX,
VRM_WPN_STG_05_PRE,
VRM_WPN_STG_END = d:VRM_WPN_STG_05_PRE,
VRM_WPN_NKT_START,
VRM_WPN_NKT_01_RAI = d:VRM_WPN_NKT_START,
VRM_WPN_NKT_01_SNA,
VRM_WPN_NKT_01_PLI,
VRM_WPN_NKT_01_TUX,
VRM_WPN_NKT_01_PRE,
VRM_WPN_NKT_02_RAI,
VRM_WPN_NKT_02_SNA,
VRM_WPN_NKT_02_PLI,
VRM_WPN_NKT_02_TUX,
VRM_WPN_NKT_02_PRE,
VRM_WPN_NKT_03_RAI,
VRM_WPN_NKT_03_SNA,
VRM_WPN_NKT_03_PLI,
VRM_WPN_NKT_03_TUX,
VRM_WPN_NKT_03_PRE,
VRM_WPN_NKT_04_RAI,
VRM_WPN_NKT_04_SNA,
VRM_WPN_NKT_04_PLI,
VRM_WPN_NKT_04_TUX,
VRM_WPN_NKT_04_PRE,
VRM_WPN_NKT_05_RAI,
VRM_WPN_NKT_05_SNA,
VRM_WPN_NKT_05_PLI,
VRM_WPN_NKT_05_TUX,
VRM_WPN_NKT_05_PRE,
VRM_WPN_NKT_END = d:VRM_WPN_NKT_05_PRE,
VRM_WPN_HFB_START,
VRM_WPN_HFB_01_RAI = d:VRM_WPN_HFB_START,
VRM_WPN_HFB_01_NIN,
VRM_WPN_HFB_01_SNA,
VRM_WPN_HFB_01_PLI,
VRM_WPN_HFB_01_TUX,
VRM_WPN_HFB_01_PRE,
VRM_WPN_HFB_02_RAI,
VRM_WPN_HFB_02_NIN,
VRM_WPN_HFB_02_SNA,
VRM_WPN_HFB_02_PLI,
VRM_WPN_HFB_02_TUX,
VRM_WPN_HFB_02_PRE,
VRM_WPN_HFB_03_RAI,
VRM_WPN_HFB_03_NIN,
VRM_WPN_HFB_03_SNA,
VRM_WPN_HFB_03_PLI,
VRM_WPN_HFB_03_TUX,
VRM_WPN_HFB_03_PRE,
VRM_WPN_HFB_04_RAI,
VRM_WPN_HFB_04_NIN,
VRM_WPN_HFB_04_SNA,
VRM_WPN_HFB_04_PLI,
VRM_WPN_HFB_04_TUX,
VRM_WPN_HFB_04_PRE,
VRM_WPN_HFB_05_RAI,
VRM_WPN_HFB_05_NIN,
VRM_WPN_HFB_05_SNA,
VRM_WPN_HFB_05_PLI,
VRM_WPN_HFB_05_TUX,
VRM_WPN_HFB_05_PRE,
VRM_WPN_HFB_END = d:VRM_WPN_HFB_05_PRE,
VRM_WPN_END = d:VRM_WPN_HFB_END,
VRM_FPV_START,
VRM_FPV_01_RAI = d:VRM_FPV_START,
VRM_FPV_01_SNA,
VRM_FPV_02_RAI,
VRM_FPV_02_SNA,
VRM_FPV_03_RAI,
VRM_FPV_03_SNA,
VRM_FPV_04_RAI,
VRM_FPV_04_SNA,
VRM_FPV_05_RAI,
VRM_FPV_05_SNA,
VRM_FPV_END = d:VRM_FPV_05_SNA,
VRM_VRT_START,
VRM_VRT_01_RAI = d:VRM_VRT_START,
VRM_VRT_01_NIN,
VRM_VRT_01_SNA,
VRM_VRT_01_PLI,
VRM_VRT_01_TUX,
VRM_VRT_01_PRE,
VRM_VRT_02_RAI,
VRM_VRT_02_NIN,
VRM_VRT_02_SNA,
VRM_VRT_02_PLI,
VRM_VRT_02_TUX,
VRM_VRT_02_PRE,
VRM_VRT_03_RAI,
VRM_VRT_03_NIN,
VRM_VRT_03_SNA,
VRM_VRT_03_PLI,
VRM_VRT_03_TUX,
VRM_VRT_03_PRE,
VRM_VRT_04_RAI,
VRM_VRT_04_NIN,
VRM_VRT_04_SNA,
VRM_VRT_04_PLI,
VRM_VRT_04_TUX,
VRM_VRT_04_PRE,
VRM_VRT_05_RAI,
VRM_VRT_05_NIN,
VRM_VRT_05_SNA,
VRM_VRT_05_PLI,
VRM_VRT_05_TUX,
VRM_VRT_05_PRE,
VRM_VRT_06_RAI,
VRM_VRT_06_NIN,
VRM_VRT_06_SNA,
VRM_VRT_06_PLI,
VRM_VRT_06_TUX,
VRM_VRT_06_PRE,
VRM_VRT_07_RAI,
VRM_VRT_07_NIN,
VRM_VRT_07_SNA,
VRM_VRT_07_PLI,
VRM_VRT_07_TUX,
VRM_VRT_07_PRE,
VRM_VRT_END = d:VRM_VRT_07_PRE,
VRM_STR_START,
VRM_STR_01_RAI = d:VRM_STR_START,
VRM_STR_END = d:VRM_STR_01_RAI,
VRM_END = d:VRM_STR_END,
ALT_START,
ALT_BMB_START = d:ALT_START,
ALT_BMB_01_RAI = d:ALT_BMB_START,
ALT_BMB_01_NIN,
ALT_BMB_01_SNA,
ALT_BMB_01_PLI,
ALT_BMB_01_TUX,
ALT_BMB_01_PRE,
ALT_BMB_02_RAI,
ALT_BMB_02_NIN,
ALT_BMB_02_SNA,
ALT_BMB_02_PLI,
ALT_BMB_02_TUX,
ALT_BMB_02_PRE,
ALT_BMB_03_RAI,
ALT_BMB_03_NIN,
ALT_BMB_03_SNA,
ALT_BMB_03_PLI,
ALT_BMB_03_TUX,
ALT_BMB_03_PRE,
ALT_BMB_04_RAI,
ALT_BMB_04_NIN,
ALT_BMB_04_SNA,
ALT_BMB_04_PLI,
ALT_BMB_04_TUX,
ALT_BMB_04_PRE,
ALT_BMB_05_RAI,
ALT_BMB_05_NIN,
ALT_BMB_05_SNA,
ALT_BMB_05_PLI,
ALT_BMB_05_TUX,
ALT_BMB_05_PRE,
ALT_BMB_END = d:ALT_BMB_05_PRE,
ALT_ELM_START,
ALT_ELM_01_RAI = d:ALT_ELM_START,
ALT_ELM_01_NIN,
ALT_ELM_01_SNA,
ALT_ELM_01_PLI,
ALT_ELM_01_TUX,
ALT_ELM_01_PRE,
ALT_ELM_02_RAI,
ALT_ELM_02_NIN,
ALT_ELM_02_SNA,
ALT_ELM_02_PLI,
ALT_ELM_02_TUX,
ALT_ELM_02_PRE,
ALT_ELM_03_RAI,
ALT_ELM_03_NIN,
ALT_ELM_03_SNA,
ALT_ELM_03_PLI,
ALT_ELM_03_TUX,
ALT_ELM_03_PRE,
ALT_ELM_04_RAI,
ALT_ELM_04_NIN,
ALT_ELM_04_SNA,
ALT_ELM_04_PLI,
ALT_ELM_04_TUX,
ALT_ELM_04_PRE,
ALT_ELM_05_RAI,
ALT_ELM_05_NIN,
ALT_ELM_05_SNA,
ALT_ELM_05_PLI,
ALT_ELM_05_TUX,
ALT_ELM_05_PRE,
ALT_ELM_06_RAI,
ALT_ELM_06_NIN,
ALT_ELM_06_SNA,
ALT_ELM_06_PLI,
ALT_ELM_06_TUX,
ALT_ELM_06_PRE,
ALT_ELM_07_RAI,
ALT_ELM_07_NIN,
ALT_ELM_07_SNA,
ALT_ELM_07_PLI,
ALT_ELM_07_TUX,
ALT_ELM_07_PRE,
ALT_ELM_08_RAI,
ALT_ELM_08_NIN,
ALT_ELM_08_SNA,
ALT_ELM_08_PLI,
ALT_ELM_08_TUX,
ALT_ELM_08_PRE,
ALT_ELM_09_RAI,
ALT_ELM_09_NIN,
ALT_ELM_09_SNA,
ALT_ELM_09_PLI,
ALT_ELM_09_TUX,
ALT_ELM_09_PRE,
ALT_ELM_10_RAI,
ALT_ELM_10_NIN,
ALT_ELM_10_SNA,
ALT_ELM_10_PLI,
ALT_ELM_10_TUX,
ALT_ELM_10_PRE,
ALT_ELM_END = d:ALT_ELM_10_PRE,
ALT_HLD_START,
ALT_HLD_01_RAI = d:ALT_HLD_START,
ALT_HLD_01_SNA,
ALT_HLD_01_PLI,
ALT_HLD_01_TUX,
ALT_HLD_01_PRE,
ALT_HLD_02_RAI,
ALT_HLD_02_SNA,
ALT_HLD_02_PLI,
ALT_HLD_02_TUX,
ALT_HLD_02_PRE,
ALT_HLD_03_RAI,
ALT_HLD_03_SNA,
ALT_HLD_03_PLI,
ALT_HLD_03_TUX,
ALT_HLD_03_PRE,
ALT_HLD_04_RAI,
ALT_HLD_04_SNA,
ALT_HLD_04_PLI,
ALT_HLD_04_TUX,
ALT_HLD_04_PRE,
ALT_HLD_05_RAI,
ALT_HLD_05_SNA,
ALT_HLD_05_PLI,
ALT_HLD_05_TUX,
ALT_HLD_05_PRE,
ALT_HLD_06_RAI,
ALT_HLD_06_SNA,
ALT_HLD_06_PLI,
ALT_HLD_06_TUX,
ALT_HLD_06_PRE,
ALT_HLD_07_RAI,
ALT_HLD_07_SNA,
ALT_HLD_07_PLI,
ALT_HLD_07_TUX,
ALT_HLD_07_PRE,
ALT_HLD_08_RAI,
ALT_HLD_08_SNA,
ALT_HLD_08_PLI,
ALT_HLD_08_TUX,
ALT_HLD_08_PRE,
ALT_HLD_09_RAI,
ALT_HLD_09_SNA,
ALT_HLD_09_PLI,
ALT_HLD_09_TUX,
ALT_HLD_09_PRE,
ALT_HLD_10_RAI,
ALT_HLD_10_SNA,
ALT_HLD_10_PLI,
ALT_HLD_10_TUX,
ALT_HLD_10_PRE,
ALT_HLD_END = d:ALT_HLD_10_PRE,
ALT_PHT_START,
ALT_PHT_01_RAI = d:ALT_PHT_START,
ALT_PHT_01_SNA,
ALT_PHT_02_RAI,
ALT_PHT_02_SNA,
ALT_PHT_03_RAI,
ALT_PHT_03_SNA,
ALT_PHT_04_RAI,
ALT_PHT_04_SNA,
ALT_PHT_05_RAI,
ALT_PHT_05_SNA,
ALT_PHT_06_RAI,
ALT_PHT_06_SNA,
ALT_PHT_07_RAI,
ALT_PHT_07_SNA,
ALT_PHT_END = d:ALT_PHT_07_SNA,
ALT_END = d:ALT_PHT_END,
MSN_STAGE_ID_MAX
};
