#
# Makefile for UVMap 
#	
#	Tue Nov 16 07:45:11 JST 1999
#	T.Morita
#
#	$Id: Makefile,v 1.1 2000/10/06 02:59:45 usr04098 Exp $
#
TARGET = allup allfix

INSTDIR = /u/develop/mj001b/tools/bin/linux

install:
	cp $(TARGET) $(INSTDIR)

