#!/bin/csh
#
# Check BMP in the KMS
#
# T.Morita 
#  $Id: check_kms_bmp,v 1.3 2001/06/19 02:16:42 usr04098 Exp $
#

find /u/develop/mj001data/fix/$1 -name '*.dar' -exec check_dar_bmp {} $2 \; | sed -e 's/dar$/mdl/'

