#
# Makefile for UVMap 
#	
#	Tue Nov 16 07:45:11 JST 1999
#	T.Morita
#
#	$Id: makefile,v 1.1 2001/11/30 04:17:50 usr04098 Exp $
#
TARGET = newdemo

INSTDIR = /u/develop/mj001b/tools/bin/linux

install:
	cp $(TARGET) $(INSTDIR)

